/// LLVM-Deklarationen aller C-Runtime-Funktionen.
/// Jede Funktion aus moo_runtime.h wird hier als LLVM-Funktion deklariert.

use inkwell::context::Context;
use inkwell::module::Module;
use inkwell::types::{BasicMetadataTypeEnum, BasicTypeEnum, StructType};
use inkwell::values::FunctionValue;
use inkwell::AddressSpace;

pub struct RuntimeBindings<'ctx> {
    pub moo_value_type: StructType<'ctx>,
    // Konstruktoren
    pub moo_number: FunctionValue<'ctx>,
    pub moo_string_new: FunctionValue<'ctx>,
    pub moo_bool_fn: FunctionValue<'ctx>,
    pub moo_none: FunctionValue<'ctx>,
    pub moo_list_new: FunctionValue<'ctx>,
    pub moo_dict_new: FunctionValue<'ctx>,
    pub moo_object_new: FunctionValue<'ctx>,
    // Ops
    pub moo_add: FunctionValue<'ctx>,
    pub moo_sub: FunctionValue<'ctx>,
    pub moo_mul: FunctionValue<'ctx>,
    pub moo_div: FunctionValue<'ctx>,
    pub moo_mod: FunctionValue<'ctx>,
    pub moo_pow: FunctionValue<'ctx>,
    pub moo_neg: FunctionValue<'ctx>,
    pub moo_eq: FunctionValue<'ctx>,
    pub moo_neq: FunctionValue<'ctx>,
    pub moo_lt: FunctionValue<'ctx>,
    pub moo_gt: FunctionValue<'ctx>,
    pub moo_lte: FunctionValue<'ctx>,
    pub moo_gte: FunctionValue<'ctx>,
    pub moo_and: FunctionValue<'ctx>,
    pub moo_or: FunctionValue<'ctx>,
    pub moo_not: FunctionValue<'ctx>,
    // Bitwise
    pub moo_bitand: FunctionValue<'ctx>,
    pub moo_bitor: FunctionValue<'ctx>,
    pub moo_bitxor: FunctionValue<'ctx>,
    pub moo_bitnot: FunctionValue<'ctx>,
    pub moo_lshift: FunctionValue<'ctx>,
    pub moo_rshift: FunctionValue<'ctx>,
    // Memory
    pub moo_mem_read: FunctionValue<'ctx>,
    pub moo_mem_write: FunctionValue<'ctx>,
    // CPU / Hardware
    pub moo_cpu_halt: FunctionValue<'ctx>,
    pub moo_cpu_cli: FunctionValue<'ctx>,
    pub moo_cpu_sti: FunctionValue<'ctx>,
    pub moo_io_inb: FunctionValue<'ctx>,
    pub moo_io_outb: FunctionValue<'ctx>,
    // P011-B1: 16/32-bit Port-I/O
    pub moo_io_inw: FunctionValue<'ctx>,
    pub moo_io_outw: FunctionValue<'ctx>,
    pub moo_io_inl: FunctionValue<'ctx>,
    pub moo_io_outl: FunctionValue<'ctx>,
    // P011-B2: CPU-Steuer-Builtins
    pub kern_rdmsr_lo: FunctionValue<'ctx>,
    pub kern_rdmsr_hi: FunctionValue<'ctx>,
    pub kern_wrmsr: FunctionValue<'ctx>,
    pub kern_cr_lese: FunctionValue<'ctx>,
    pub kern_cr_setze: FunctionValue<'ctx>,
    pub kern_lgdt: FunctionValue<'ctx>,
    pub kern_lidt: FunctionValue<'ctx>,
    // Kernel (bare-metal, kern_* — Plan-010)
    pub kern_seriell_init: FunctionValue<'ctx>,
    pub kern_seriell_zeichen: FunctionValue<'ctx>,
    pub kern_seriell_dez: FunctionValue<'ctx>,
    pub kern_seriell_hex: FunctionValue<'ctx>,
    pub kern_vga_init: FunctionValue<'ctx>,
    pub kern_vga_farbe: FunctionValue<'ctx>,
    pub kern_vga_zeichen: FunctionValue<'ctx>,
    pub kern_speicher_init: FunctionValue<'ctx>,
    pub kern_alloc: FunctionValue<'ctx>,
    pub kern_frei: FunctionValue<'ctx>,
    pub kern_speicher_frei: FunctionValue<'ctx>,
    pub kern_speicher_belegt: FunctionValue<'ctx>,
    pub kern_speicher_peak: FunctionValue<'ctx>,
    pub kern_idt_init: FunctionValue<'ctx>,
    pub kern_pic_remap: FunctionValue<'ctx>,
    pub kern_pic_maskiere: FunctionValue<'ctx>,
    pub kern_pic_demaskiere: FunctionValue<'ctx>,
    pub kern_pic_eoi: FunctionValue<'ctx>,
    pub kern_timer_init: FunctionValue<'ctx>,
    pub kern_ticks: FunctionValue<'ctx>,
    pub kern_stackprot_selbsttest: FunctionValue<'ctx>,
    // String
    pub moo_string_concat: FunctionValue<'ctx>,
    // List
    pub moo_list_append: FunctionValue<'ctx>,
    pub moo_list_length: FunctionValue<'ctx>,
    pub moo_list_pop: FunctionValue<'ctx>,
    pub moo_list_sort: FunctionValue<'ctx>,
    pub moo_list_reverse: FunctionValue<'ctx>,
    pub moo_list_join: FunctionValue<'ctx>,
    pub moo_list_iter_len: FunctionValue<'ctx>,
    pub moo_list_iter_get: FunctionValue<'ctx>,
    // Dict
    pub moo_dict_get: FunctionValue<'ctx>,
    pub moo_dict_set: FunctionValue<'ctx>,
    pub moo_dict_has: FunctionValue<'ctx>,
    pub moo_dict_keys: FunctionValue<'ctx>,
    // Object
    pub moo_object_get: FunctionValue<'ctx>,
    pub moo_object_set: FunctionValue<'ctx>,
    pub moo_object_class_name: FunctionValue<'ctx>,
    pub moo_smart_close: FunctionValue<'ctx>,
    pub moo_smart_contains: FunctionValue<'ctx>,
    pub moo_socket_set_timeout: FunctionValue<'ctx>,
    pub moo_socket_read_bytes: FunctionValue<'ctx>,
    pub moo_socket_write_bytes: FunctionValue<'ctx>,
    pub moo_bytes_to_string: FunctionValue<'ctx>,
    pub moo_string_to_bytes: FunctionValue<'ctx>,
    // Events
    pub moo_event_on: FunctionValue<'ctx>,
    pub moo_event_emit: FunctionValue<'ctx>,
    // Print & convert
    pub moo_print: FunctionValue<'ctx>,
    pub moo_to_string: FunctionValue<'ctx>,
    // Error & truthiness
    pub moo_throw: FunctionValue<'ctx>,
    pub moo_try_enter: FunctionValue<'ctx>,
    pub moo_try_check: FunctionValue<'ctx>,
    pub moo_try_leave: FunctionValue<'ctx>,
    pub moo_get_error: FunctionValue<'ctx>,
    pub moo_is_truthy: FunctionValue<'ctx>,
    pub moo_is_none: FunctionValue<'ctx>,
    // Reference Counting
    pub moo_retain: FunctionValue<'ctx>,
    pub moo_release: FunctionValue<'ctx>,
    // Stdlib
    // String extras
    pub moo_string_upper: FunctionValue<'ctx>,
    pub moo_string_lower: FunctionValue<'ctx>,
    pub moo_string_trim: FunctionValue<'ctx>,
    pub moo_string_split: FunctionValue<'ctx>,
    pub moo_string_replace: FunctionValue<'ctx>,
    pub moo_string_contains: FunctionValue<'ctx>,
    pub moo_string_slice: FunctionValue<'ctx>,
    // Stdlib
    pub moo_abs: FunctionValue<'ctx>,
    pub moo_sqrt: FunctionValue<'ctx>,
    pub moo_sin: FunctionValue<'ctx>,
    pub moo_cos: FunctionValue<'ctx>,
    pub moo_tan: FunctionValue<'ctx>,
    pub moo_atan2: FunctionValue<'ctx>,
    pub moo_round: FunctionValue<'ctx>,
    pub moo_floor: FunctionValue<'ctx>,
    pub moo_ceil: FunctionValue<'ctx>,
    pub moo_min: FunctionValue<'ctx>,
    pub moo_max: FunctionValue<'ctx>,
    pub moo_random: FunctionValue<'ctx>,
    pub moo_type_of: FunctionValue<'ctx>,
    pub moo_input: FunctionValue<'ctx>,
    pub moo_length: FunctionValue<'ctx>,
    pub moo_range: FunctionValue<'ctx>,
    pub moo_time: FunctionValue<'ctx>,
    pub moo_time_ms: FunctionValue<'ctx>,
    pub moo_ki_gpu_statistik: FunctionValue<'ctx>,
    pub moo_ki_gpu_statistik_reset: FunctionValue<'ctx>,
    pub moo_syscall: FunctionValue<'ctx>,
    pub moo_breakpoint: FunctionValue<'ctx>,
    pub moo_index_get: FunctionValue<'ctx>,
    pub moo_index_set: FunctionValue<'ctx>,
    // Freeze/Immutable
    pub moo_freeze: FunctionValue<'ctx>,
    pub moo_is_frozen: FunctionValue<'ctx>,
    // File I/O
    pub moo_file_read: FunctionValue<'ctx>,
    pub moo_file_write: FunctionValue<'ctx>,
    pub moo_file_read_bytes: FunctionValue<'ctx>,
    pub moo_file_write_bytes: FunctionValue<'ctx>,
    pub moo_file_append: FunctionValue<'ctx>,
    pub moo_file_lines: FunctionValue<'ctx>,
    pub moo_file_exists: FunctionValue<'ctx>,
    pub moo_file_delete: FunctionValue<'ctx>,
    pub moo_file_mtime: FunctionValue<'ctx>,
    pub moo_file_is_dir: FunctionValue<'ctx>,
    pub moo_file_mkdir: FunctionValue<'ctx>,
    pub moo_dir_list: FunctionValue<'ctx>,
    // First-Class Funktionen (MOO_FUNC-Constructors + Helpers)
    pub moo_func_new: FunctionValue<'ctx>,
    pub moo_func_with_captures: FunctionValue<'ctx>,
    pub moo_func_captured_at: FunctionValue<'ctx>,
    pub moo_func_call_0: FunctionValue<'ctx>,
    pub moo_func_call_1: FunctionValue<'ctx>,
    pub moo_func_call_2: FunctionValue<'ctx>,
    pub moo_func_call_3: FunctionValue<'ctx>,
    pub moo_func_call_4: FunctionValue<'ctx>,
    pub moo_func_call_5: FunctionValue<'ctx>,
    pub moo_func_call_6: FunctionValue<'ctx>,
    pub moo_func_call_7: FunctionValue<'ctx>,
    pub moo_func_call_8: FunctionValue<'ctx>,
    // Thread & Channel
    pub moo_thread_spawn: FunctionValue<'ctx>,
    pub moo_thread_wait: FunctionValue<'ctx>,
    pub moo_thread_done: FunctionValue<'ctx>,
    pub moo_channel_new: FunctionValue<'ctx>,
    pub moo_channel_send: FunctionValue<'ctx>,
    pub moo_channel_recv: FunctionValue<'ctx>,
    // JSON
    pub moo_json_parse: FunctionValue<'ctx>,
    pub moo_json_string: FunctionValue<'ctx>,
    // HTTP
    pub moo_http_get: FunctionValue<'ctx>,
    pub moo_http_post: FunctionValue<'ctx>,
    pub moo_http_get_with_headers: FunctionValue<'ctx>,
    pub moo_http_post_with_headers: FunctionValue<'ctx>,
    // Crypto & Security
    pub moo_sha256: FunctionValue<'ctx>,
    pub moo_sha256_bytes: FunctionValue<'ctx>,
    pub moo_sha1: FunctionValue<'ctx>,
    pub moo_sha1_bytes: FunctionValue<'ctx>,
    pub moo_hmac_sha256: FunctionValue<'ctx>,
    pub moo_pbkdf2_sha256: FunctionValue<'ctx>,
    pub moo_secure_random: FunctionValue<'ctx>,
    // === Tensor (Plan-014 A3) ===
    pub moo_tensor_neu: FunctionValue<'ctx>,
    pub moo_tensor_nullen: FunctionValue<'ctx>,
    pub moo_tensor_einsen: FunctionValue<'ctx>,
    pub moo_tensor_zufall: FunctionValue<'ctx>,
    pub moo_tensor_aus_liste: FunctionValue<'ctx>,
    pub moo_tensor_holen: FunctionValue<'ctx>,
    pub moo_tensor_setzen: FunctionValue<'ctx>,
    pub moo_tensor_form: FunctionValue<'ctx>,
    pub moo_tensor_groesse: FunctionValue<'ctx>,
    pub moo_tensor_zu_liste: FunctionValue<'ctx>,
    pub moo_tensor_add: FunctionValue<'ctx>,
    pub moo_tensor_sub: FunctionValue<'ctx>,
    pub moo_tensor_mul: FunctionValue<'ctx>,
    pub moo_tensor_div: FunctionValue<'ctx>,
    pub moo_tensor_adds: FunctionValue<'ctx>,
    pub moo_tensor_subs: FunctionValue<'ctx>,
    pub moo_tensor_muls: FunctionValue<'ctx>,
    pub moo_tensor_divs: FunctionValue<'ctx>,
    pub moo_tensor_matmul: FunctionValue<'ctx>,
    pub moo_tensor_transponieren: FunctionValue<'ctx>,
    pub moo_tensor_umformen: FunctionValue<'ctx>,
    pub moo_tensor_zeilen: FunctionValue<'ctx>,
    pub moo_tensor_verbinden: FunctionValue<'ctx>,
    pub moo_tensor_summe: FunctionValue<'ctx>,
    pub moo_tensor_mittel: FunctionValue<'ctx>,
    pub moo_tensor_maximum: FunctionValue<'ctx>,
    pub moo_tensor_exp: FunctionValue<'ctx>,
    pub moo_tensor_log: FunctionValue<'ctx>,
    pub moo_tensor_sqrt: FunctionValue<'ctx>,
    pub moo_tensor_neg: FunctionValue<'ctx>,
    pub moo_tensor_pow: FunctionValue<'ctx>,
    pub moo_tensor_relu: FunctionValue<'ctx>,
    pub moo_tensor_sigmoid: FunctionValue<'ctx>,
    pub moo_tensor_tanh: FunctionValue<'ctx>,
    pub moo_tensor_gelu: FunctionValue<'ctx>,
    pub moo_tensor_softmax: FunctionValue<'ctx>,
    pub moo_tensor_logsoftmax: FunctionValue<'ctx>,
    pub moo_tensor_als_dtype: FunctionValue<'ctx>,   // D1: f32<->bf16 Storage-Konvertierung
    // === Autograd (Plan-014 B1) ===
    pub moo_tensor_mit_gradient: FunctionValue<'ctx>,
    pub moo_tensor_rueckwaerts: FunctionValue<'ctx>,
    pub moo_tensor_gradient: FunctionValue<'ctx>,
    pub moo_tensor_gradient_loeschen: FunctionValue<'ctx>,
    pub moo_ag_reset: FunctionValue<'ctx>,
    pub moo_ag_an: FunctionValue<'ctx>,
    pub moo_ag_aus: FunctionValue<'ctx>,
    // === NN-Schichten + Loss + Optimizer (Plan-014 C1) ===
    pub moo_nn_schicht_dicht: FunctionValue<'ctx>,
    pub moo_nn_schicht_faltung: FunctionValue<'ctx>,
    pub moo_nn_schicht_pooling: FunctionValue<'ctx>,
    pub moo_nn_schicht_flach: FunctionValue<'ctx>,
    pub moo_nn_schicht_dropout: FunctionValue<'ctx>,
    pub moo_nn_schicht_layernorm: FunctionValue<'ctx>,
    pub moo_nn_schicht_rmsnorm: FunctionValue<'ctx>,
    pub moo_nn_schicht_ffn_gated: FunctionValue<'ctx>,
    pub moo_nn_schicht_embedding: FunctionValue<'ctx>,
    pub moo_nn_schicht_attention: FunctionValue<'ctx>,
    pub moo_nn_schicht_position: FunctionValue<'ctx>,
    pub moo_nn_schicht_moe: FunctionValue<'ctx>,
    pub moo_nn_moe_balance: FunctionValue<'ctx>,
    pub moo_nn_cache_leeren: FunctionValue<'ctx>,
    pub moo_nn_sequence_packen: FunctionValue<'ctx>,
    pub moo_nn_packung_setzen: FunctionValue<'ctx>,
    pub moo_nn_packung_leeren: FunctionValue<'ctx>,
    pub moo_nn_vorwaerts: FunctionValue<'ctx>,
    pub moo_nn_parameter: FunctionValue<'ctx>,
    pub moo_nn_mse: FunctionValue<'ctx>,
    pub moo_nn_kosinus: FunctionValue<'ctx>,
    pub moo_nn_kontrastiv: FunctionValue<'ctx>,
    pub moo_nn_kreuzentropie: FunctionValue<'ctx>,
    pub moo_nn_kreuzentropie_maskiert: FunctionValue<'ctx>,
    pub moo_nn_opt_sgd: FunctionValue<'ctx>,
    pub moo_nn_opt_adam: FunctionValue<'ctx>,
    pub moo_nn_opt_adamw: FunctionValue<'ctx>,
    pub moo_nn_opt_schritt: FunctionValue<'ctx>,
    pub moo_nn_grad_clip: FunctionValue<'ctx>,
    // Kinderleicht-API (Plan-014 D1)
    pub moo_nn_ki_netz: FunctionValue<'ctx>,
    pub moo_nn_trainiere: FunctionValue<'ctx>,
    pub moo_nn_vorhersage: FunctionValue<'ctx>,
    pub moo_nn_genauigkeit: FunctionValue<'ctx>,
    pub moo_nn_speichern: FunctionValue<'ctx>,
    pub moo_nn_laden: FunctionValue<'ctx>,
    pub moo_nn_safetensors: FunctionValue<'ctx>,
    // KIP-E2: CPU-Voll-Checkpoint v2
    pub moo_nn_ckpt_speichern: FunctionValue<'ctx>,
    pub moo_nn_ckpt_laden: FunctionValue<'ctx>,
    pub moo_nn_ckpt_rotieren: FunctionValue<'ctx>,
    // Daten-Pipeline (Plan-014 E1)
    pub moo_ds_mnist: FunctionValue<'ctx>,
    pub moo_ds_csv: FunctionValue<'ctx>,
    pub moo_ds_bild: FunctionValue<'ctx>,
    pub moo_ds_mischen: FunctionValue<'ctx>,
    pub moo_ds_normalisieren: FunctionValue<'ctx>,
    pub moo_ds_tokenizer: FunctionValue<'ctx>,
    // Byte-level BPE-Tokenizer (KIP-T2)
    pub moo_tok_trainiere: FunctionValue<'ctx>,
    pub moo_tok_kodiere: FunctionValue<'ctx>,
    pub moo_tok_dekodiere: FunctionValue<'ctx>,
    pub moo_tok_kodiere_stapel: FunctionValue<'ctx>,
    pub moo_tok_speichern: FunctionValue<'ctx>,
    pub moo_tok_laden: FunctionValue<'ctx>,
    pub moo_tok_info: FunctionValue<'ctx>,
    pub moo_tok_hash: FunctionValue<'ctx>,
    // KIP-T3: Chat-/Special-Tokens + Render
    pub moo_tok_chat_init: FunctionValue<'ctx>,
    pub moo_tok_spezial_id: FunctionValue<'ctx>,
    pub moo_tok_rendern: FunctionValue<'ctx>,
    // KIP-E1: Streaming-Token-Shards + Dataloader
    pub moo_shard_schreiben: FunctionValue<'ctx>,
    pub moo_shard_info: FunctionValue<'ctx>,
    pub moo_shard_pruefen: FunctionValue<'ctx>,
    pub moo_shard_fenster: FunctionValue<'ctx>,
    pub moo_shard_fenster_maske: FunctionValue<'ctx>,
    pub moo_shard_reihenfolge: FunctionValue<'ctx>,
    pub moo_shard_split: FunctionValue<'ctx>,
    pub moo_base64_encode: FunctionValue<'ctx>,
    pub moo_base64_decode: FunctionValue<'ctx>,
    pub moo_sanitize_html: FunctionValue<'ctx>,
    pub moo_sanitize_sql: FunctionValue<'ctx>,
    // Database
    pub moo_db_connect: FunctionValue<'ctx>,
    pub moo_db_execute: FunctionValue<'ctx>,
    pub moo_db_query: FunctionValue<'ctx>,
    pub moo_db_close: FunctionValue<'ctx>,
    pub moo_db_execute_with_params: FunctionValue<'ctx>,
    pub moo_db_query_with_params: FunctionValue<'ctx>,
    // Hybrid 2D+3D Pipeline (M5)
    pub moo_hybrid_create: FunctionValue<'ctx>,
    pub moo_hybrid_is_open: FunctionValue<'ctx>,
    pub moo_hybrid_clear: FunctionValue<'ctx>,
    pub moo_hybrid_update: FunctionValue<'ctx>,
    pub moo_hybrid_close: FunctionValue<'ctx>,
    pub moo_hybrid_rect_z: FunctionValue<'ctx>,
    pub moo_hybrid_line_z: FunctionValue<'ctx>,
    pub moo_hybrid_circle_z: FunctionValue<'ctx>,
    pub moo_hybrid_sprite_z: FunctionValue<'ctx>,
    pub moo_hybrid_sprite_load: FunctionValue<'ctx>,
    pub moo_db_prepare: FunctionValue<'ctx>,
    pub moo_db_stmt_bind: FunctionValue<'ctx>,
    pub moo_db_stmt_step: FunctionValue<'ctx>,
    pub moo_db_stmt_execute: FunctionValue<'ctx>,
    pub moo_db_stmt_query: FunctionValue<'ctx>,
    pub moo_db_stmt_reset: FunctionValue<'ctx>,
    // 3D Input
    pub moo_3d_key_pressed: FunctionValue<'ctx>,
    pub moo_3d_capture_mouse: FunctionValue<'ctx>,
    pub moo_3d_light: FunctionValue<'ctx>,
    pub moo_3d_ambient: FunctionValue<'ctx>,
    pub moo_3d_fog: FunctionValue<'ctx>,
    pub moo_3d_fog_color: FunctionValue<'ctx>,
    pub moo_3d_sky: FunctionValue<'ctx>,
    pub moo_3d_triangle_colors: FunctionValue<'ctx>,
    pub moo_3d_alpha: FunctionValue<'ctx>,
    pub moo_3d_wave: FunctionValue<'ctx>,
    pub moo_3d_light_color: FunctionValue<'ctx>,
    pub moo_3d_spec: FunctionValue<'ctx>,
    pub moo_3d_clear_hex: FunctionValue<'ctx>,
    pub moo_3d_time_of_day: FunctionValue<'ctx>,
    pub moo_3d_release_mouse: FunctionValue<'ctx>,
    pub moo_3d_mouse_dx: FunctionValue<'ctx>,
    pub moo_3d_mouse_dy: FunctionValue<'ctx>,
    // Voxel-Welt (Plan-005 Phase 1a Kern). Wie alle 3D-Builtins UNBEDINGT
    // deklariert (kein #[cfg]); Gating erfolgt rein auf C-Link-Ebene via build.rs.
    pub moo_voxel_welt_neu: FunctionValue<'ctx>,
    pub moo_voxel_generieren: FunctionValue<'ctx>,
    pub moo_voxel_setzen: FunctionValue<'ctx>,
    pub moo_voxel_holen: FunctionValue<'ctx>,
    pub moo_voxel_ram_statistik: FunctionValue<'ctx>,
    // Voxel-Optimize (Plan-006 R3): expliziter Section-Downgrade-Lauf.
    pub moo_voxel_welt_optimieren: FunctionValue<'ctx>,
    // Voxel-Mesher (Plan-005 Phase 1b, CG2 nach RT2). Ebenfalls UNBEDINGT
    // deklariert; Gating rein auf C-Link-Ebene via build.rs (kein Link-Bruch
    // im Non-3D-Build, solange der Builtin im moo-Programm ungenutzt bleibt).
    pub moo_voxel_mesh_bauen: FunctionValue<'ctx>,
    pub moo_voxel_aktualisieren: FunctionValue<'ctx>,
    // Voxel-Raycast/AABB (Plan-005 Phase 1d, CG3 nach RT4). Ebenfalls UNBEDINGT
    // deklariert; Gating rein auf C-Link-Ebene via build.rs (kein Link-Bruch
    // im Non-3D-Build, solange der Builtin im moo-Programm ungenutzt bleibt).
    pub moo_voxel_strahl: FunctionValue<'ctx>,
    pub moo_voxel_aabb: FunctionValue<'ctx>,
    pub moo_3d_mouse_x: FunctionValue<'ctx>,
    pub moo_3d_mouse_y: FunctionValue<'ctx>,
    pub moo_3d_mouse_button: FunctionValue<'ctx>,
    pub moo_3d_mouse_wheel: FunctionValue<'ctx>,
    pub moo_3d_simulate_mouse_pos: FunctionValue<'ctx>,
    pub moo_3d_simulate_mouse_button: FunctionValue<'ctx>,
    pub moo_3d_simulate_scroll: FunctionValue<'ctx>,
    pub moo_3d_simulate_key: FunctionValue<'ctx>,
    pub moo_3d_simulate_mouse_delta: FunctionValue<'ctx>,
    pub moo_3d_simulate_reset: FunctionValue<'ctx>,
    pub moo_3d_screenshot_bmp: FunctionValue<'ctx>,
    // Einheitlicher Test-API-Layer (Plan-008 A2, tag-dispatch 2D/3D/Hybrid)
    pub moo_test_sim_taste: FunctionValue<'ctx>,
    pub moo_test_sim_maus_pos: FunctionValue<'ctx>,
    pub moo_test_sim_maus_taste: FunctionValue<'ctx>,
    pub moo_test_sim_maus_rad: FunctionValue<'ctx>,
    pub moo_test_sim_maus_delta: FunctionValue<'ctx>,
    pub moo_test_sim_reset: FunctionValue<'ctx>,
    pub moo_test_screenshot: FunctionValue<'ctx>,
    pub moo_test_fenster_info: FunctionValue<'ctx>,
    // Frame-Grab / Pixel (Plan-008 A3A, opaker MOO_FRAME-Heap-Typ)
    pub moo_test_frame_grab: FunctionValue<'ctx>,
    pub moo_test_pixel: FunctionValue<'ctx>,
    pub moo_test_frame_save_bmp: FunctionValue<'ctx>,
    pub moo_test_frame_diff: FunctionValue<'ctx>,
    pub moo_test_frame_region: FunctionValue<'ctx>,
    pub moo_test_frame_save_png: FunctionValue<'ctx>,
    pub moo_tensor_aus_frame: FunctionValue<'ctx>,
    pub moo_frame_aus_tensor: FunctionValue<'ctx>,
    // Audio-Feature-Extraktion (KI-MULTI-A1, SDL-frei, kein Autograd).
    pub moo_fft: FunctionValue<'ctx>,
    pub moo_spektrum_betrag: FunctionValue<'ctx>,
    pub moo_spektrogramm: FunctionValue<'ctx>,
    pub moo_wav_lesen: FunctionValue<'ctx>,
    // GIF-Recorder (Plan-008 A3B): start(win/frame,pfad,fps)->MOO_GIF,
    // frame(gif,win/frame)->Bool, ende(gif)->Bool.
    pub moo_test_gif_start: FunctionValue<'ctx>,
    pub moo_test_gif_frame: FunctionValue<'ctx>,
    pub moo_test_gif_ende: FunctionValue<'ctx>,
    // MP4-Video-Recorder (Plan-009 V1). Symbole immer deklariert; C-seitig
    // in moo_test_api.c (3D-Build) gelinkt. Pipe-Kern (moo_video.c) + Heap-
    // Wrapper (moo_video_handle.c) sind Core-Build, daher immer verfuegbar.
    pub moo_test_video_start: FunctionValue<'ctx>,
    pub moo_test_video_frame: FunctionValue<'ctx>,
    pub moo_test_video_ende: FunctionValue<'ctx>,
    // Chunk Display Lists
    pub moo_3d_chunk_create: FunctionValue<'ctx>,
    pub moo_3d_chunk_begin: FunctionValue<'ctx>,
    pub moo_3d_chunk_end: FunctionValue<'ctx>,
    pub moo_3d_chunk_draw: FunctionValue<'ctx>,
    pub moo_3d_chunk_delete: FunctionValue<'ctx>,
    // Welt (Game-Dev Runtime)
    pub moo_world_create: FunctionValue<'ctx>,
    pub moo_world_is_open: FunctionValue<'ctx>,
    pub moo_world_update: FunctionValue<'ctx>,
    pub moo_world_close: FunctionValue<'ctx>,
    pub moo_world_seed: FunctionValue<'ctx>,
    pub moo_world_biome: FunctionValue<'ctx>,
    pub moo_world_trees: FunctionValue<'ctx>,
    pub moo_world_sun: FunctionValue<'ctx>,
    pub moo_world_fog: FunctionValue<'ctx>,
    pub moo_world_sea_level: FunctionValue<'ctx>,
    pub moo_world_render_dist: FunctionValue<'ctx>,
    pub moo_world_height_at: FunctionValue<'ctx>,
    pub moo_world_time_of_day: FunctionValue<'ctx>,
    // Test-API
    pub moo_screenshot: FunctionValue<'ctx>,
    pub moo_simulate_key: FunctionValue<'ctx>,
    pub moo_simulate_mouse: FunctionValue<'ctx>,
    // Sprites (SDL2_image)
    pub moo_sprite_load: FunctionValue<'ctx>,
    pub moo_sprite_draw: FunctionValue<'ctx>,
    pub moo_sprite_draw_scaled: FunctionValue<'ctx>,
    pub moo_sprite_draw_region: FunctionValue<'ctx>,
    pub moo_sprite_width: FunctionValue<'ctx>,
    pub moo_sprite_height: FunctionValue<'ctx>,
    pub moo_sprite_free: FunctionValue<'ctx>,
    // Result-Typ
    pub moo_result_ok: FunctionValue<'ctx>,
    pub moo_result_err: FunctionValue<'ctx>,
    pub moo_result_is_ok: FunctionValue<'ctx>,
    pub moo_result_is_err: FunctionValue<'ctx>,
    pub moo_result_unwrap: FunctionValue<'ctx>,
    // Grafik (SDL2)
    pub moo_window_create: FunctionValue<'ctx>,
    pub moo_window_clear: FunctionValue<'ctx>,
    pub moo_window_update: FunctionValue<'ctx>,
    pub moo_window_is_open: FunctionValue<'ctx>,
    pub moo_window_close: FunctionValue<'ctx>,
    pub moo_draw_rect: FunctionValue<'ctx>,
    pub moo_draw_circle: FunctionValue<'ctx>,
    pub moo_draw_line: FunctionValue<'ctx>,
    pub moo_draw_pixel: FunctionValue<'ctx>,
    // Grafik Input (SDL2)
    pub moo_key_pressed: FunctionValue<'ctx>,
    pub moo_mouse_x: FunctionValue<'ctx>,
    pub moo_mouse_y: FunctionValue<'ctx>,
    pub moo_mouse_pressed: FunctionValue<'ctx>,
    pub moo_delay: FunctionValue<'ctx>,
    pub moo_pump_events: FunctionValue<'ctx>,
    // 3D Grafik (OpenGL/Software)
    pub moo_3d_create: FunctionValue<'ctx>,
    pub moo_3d_is_open: FunctionValue<'ctx>,
    pub moo_3d_clear: FunctionValue<'ctx>,
    pub moo_3d_update: FunctionValue<'ctx>,
    pub moo_3d_close: FunctionValue<'ctx>,
    pub moo_3d_perspective: FunctionValue<'ctx>,
    pub moo_3d_camera: FunctionValue<'ctx>,
    pub moo_3d_rotate: FunctionValue<'ctx>,
    pub moo_3d_translate: FunctionValue<'ctx>,
    pub moo_3d_push: FunctionValue<'ctx>,
    pub moo_3d_pop: FunctionValue<'ctx>,
    pub moo_3d_triangle: FunctionValue<'ctx>,
    pub moo_3d_cube: FunctionValue<'ctx>,
    pub moo_3d_sphere: FunctionValue<'ctx>,
    // Regex (POSIX)
    pub moo_regex_new: FunctionValue<'ctx>,
    pub moo_regex_match: FunctionValue<'ctx>,
    pub moo_regex_find: FunctionValue<'ctx>,
    pub moo_regex_find_all: FunctionValue<'ctx>,
    pub moo_regex_replace: FunctionValue<'ctx>,
    // Kern-Builtins
    pub moo_sleep: FunctionValue<'ctx>,
    pub moo_env: FunctionValue<'ctx>,
    pub moo_exit: FunctionValue<'ctx>,
    pub moo_to_number: FunctionValue<'ctx>,
    pub moo_args: FunctionValue<'ctx>,
    pub moo_pid: FunctionValue<'ctx>,
    // Tray (System-Tray) — erweitert (moo_tray.h)
    pub moo_tray_create: FunctionValue<'ctx>,
    pub moo_tray_titel_setze: FunctionValue<'ctx>,
    pub moo_tray_icon_setze: FunctionValue<'ctx>,
    pub moo_tray_aktiv: FunctionValue<'ctx>,
    pub moo_tray_menu_add: FunctionValue<'ctx>,
    pub moo_tray_separator_add: FunctionValue<'ctx>,
    pub moo_tray_menu_clear: FunctionValue<'ctx>,
    pub moo_tray_submenu_add: FunctionValue<'ctx>,
    pub moo_tray_menu_add_to: FunctionValue<'ctx>,
    pub moo_tray_separator_add_to: FunctionValue<'ctx>,
    pub moo_tray_check_add: FunctionValue<'ctx>,
    pub moo_tray_check_add_to: FunctionValue<'ctx>,
    pub moo_tray_check_wert: FunctionValue<'ctx>,
    pub moo_tray_check_set: FunctionValue<'ctx>,
    pub moo_tray_item_aktiv: FunctionValue<'ctx>,
    pub moo_tray_item_label_setze: FunctionValue<'ctx>,
    pub moo_tray_timer_add: FunctionValue<'ctx>,
    pub moo_tray_timer_remove: FunctionValue<'ctx>,
    pub moo_tray_run: FunctionValue<'ctx>,
    // UI (Cross-Platform Widgets — moo_ui.h)
    pub moo_ui_init: FunctionValue<'ctx>,
    pub moo_ui_laufen: FunctionValue<'ctx>,
    pub moo_ui_beenden: FunctionValue<'ctx>,
    pub moo_ui_pump: FunctionValue<'ctx>,
    pub moo_ui_debug: FunctionValue<'ctx>,
    pub moo_ui_fenster: FunctionValue<'ctx>,
    pub moo_ui_fenster_titel_setze: FunctionValue<'ctx>,
    pub moo_ui_fenster_icon_setze: FunctionValue<'ctx>,
    pub moo_ui_fenster_groesse_setze: FunctionValue<'ctx>,
    pub moo_ui_fenster_position_setze: FunctionValue<'ctx>,
    pub moo_ui_fenster_schliessen: FunctionValue<'ctx>,
    pub moo_ui_zeige: FunctionValue<'ctx>,
    pub moo_ui_zeige_nebenbei: FunctionValue<'ctx>,
    pub moo_ui_fenster_on_close: FunctionValue<'ctx>,
    pub moo_ui_fenster_on_resize: FunctionValue<'ctx>,
    pub moo_ui_label: FunctionValue<'ctx>,
    pub moo_ui_label_setze: FunctionValue<'ctx>,
    pub moo_ui_label_text: FunctionValue<'ctx>,
    pub moo_ui_knopf: FunctionValue<'ctx>,
    pub moo_ui_checkbox: FunctionValue<'ctx>,
    pub moo_ui_checkbox_wert: FunctionValue<'ctx>,
    pub moo_ui_checkbox_setze: FunctionValue<'ctx>,
    pub moo_ui_radio: FunctionValue<'ctx>,
    pub moo_ui_radio_wert: FunctionValue<'ctx>,
    pub moo_ui_eingabe: FunctionValue<'ctx>,
    pub moo_ui_eingabe_text: FunctionValue<'ctx>,
    pub moo_ui_eingabe_setze: FunctionValue<'ctx>,
    pub moo_ui_eingabe_on_change: FunctionValue<'ctx>,
    pub moo_ui_eingabe_on_enter: FunctionValue<'ctx>,
    pub moo_ui_textbereich: FunctionValue<'ctx>,
    pub moo_ui_textbereich_text: FunctionValue<'ctx>,
    pub moo_ui_textbereich_setze: FunctionValue<'ctx>,
    pub moo_ui_textbereich_anhaengen: FunctionValue<'ctx>,
    pub moo_ui_textbereich_on_key: FunctionValue<'ctx>,
    pub moo_ui_textbereich_zeile_anzahl: FunctionValue<'ctx>,
    pub moo_ui_dropdown: FunctionValue<'ctx>,
    pub moo_ui_dropdown_auswahl: FunctionValue<'ctx>,
    pub moo_ui_dropdown_auswahl_setze: FunctionValue<'ctx>,
    pub moo_ui_dropdown_text: FunctionValue<'ctx>,
    pub moo_ui_liste: FunctionValue<'ctx>,
    pub moo_ui_liste_zeile_hinzu: FunctionValue<'ctx>,
    pub moo_ui_liste_zeilen_hinzu_bulk: FunctionValue<'ctx>,
    pub moo_ui_liste_auswahl: FunctionValue<'ctx>,
    pub moo_ui_liste_zeile: FunctionValue<'ctx>,
    pub moo_ui_liste_leeren: FunctionValue<'ctx>,
    pub moo_ui_liste_on_auswahl: FunctionValue<'ctx>,
    pub moo_ui_liste_on_scroll: FunctionValue<'ctx>,
    pub moo_ui_liste_scroll_zu: FunctionValue<'ctx>,
    pub moo_ui_liste_scroll_unten: FunctionValue<'ctx>,
    pub moo_ui_liste_spalte_breite: FunctionValue<'ctx>,
    pub moo_ui_liste_spalte_min_breite: FunctionValue<'ctx>,
    pub moo_ui_liste_spalten_autosize: FunctionValue<'ctx>,
    pub moo_ui_liste_spalte_breite_lese: FunctionValue<'ctx>,
    pub moo_ui_liste_ist_unten: FunctionValue<'ctx>,
    pub moo_ui_liste_on_rechtsklick: FunctionValue<'ctx>,
    pub moo_ui_clipboard_setze: FunctionValue<'ctx>,
    pub moo_ui_menue_eintrag_data: FunctionValue<'ctx>,
    pub moo_ui_menue_eintrag_lookup: FunctionValue<'ctx>,
    pub moo_ui_menue_eintrag_aktiv: FunctionValue<'ctx>,
    pub moo_ui_zeit_jetzt: FunctionValue<'ctx>,
    pub moo_ui_zeit_lokal: FunctionValue<'ctx>,
    pub moo_ui_zeit_format: FunctionValue<'ctx>,
    pub moo_ui_liste_sortierbar: FunctionValue<'ctx>,
    pub moo_ui_liste_sortiere: FunctionValue<'ctx>,
    pub moo_ui_liste_zeile_setze: FunctionValue<'ctx>,
    pub moo_ui_liste_zelle_setze: FunctionValue<'ctx>,
    pub moo_ui_liste_entferne: FunctionValue<'ctx>,
    pub moo_ui_slider: FunctionValue<'ctx>,
    pub moo_ui_slider_wert: FunctionValue<'ctx>,
    pub moo_ui_slider_setze: FunctionValue<'ctx>,
    pub moo_ui_fortschritt: FunctionValue<'ctx>,
    pub moo_ui_fortschritt_setze: FunctionValue<'ctx>,
    pub moo_ui_bild: FunctionValue<'ctx>,
    pub moo_ui_bild_setze: FunctionValue<'ctx>,
    pub moo_ui_leinwand: FunctionValue<'ctx>,
    pub moo_ui_leinwand_anfordern: FunctionValue<'ctx>,
    pub moo_ui_leinwand_on_maus: FunctionValue<'ctx>,
    pub moo_ui_leinwand_on_bewegung: FunctionValue<'ctx>,
    pub moo_ui_zeichne_farbe: FunctionValue<'ctx>,
    pub moo_ui_zeichne_linie: FunctionValue<'ctx>,
    pub moo_ui_zeichne_rechteck: FunctionValue<'ctx>,
    pub moo_ui_zeichne_kreis: FunctionValue<'ctx>,
    pub moo_ui_zeichne_text: FunctionValue<'ctx>,
    pub moo_ui_zeichne_text_breite: FunctionValue<'ctx>,
    pub moo_ui_zeichne_bild: FunctionValue<'ctx>,
    pub moo_ui_rahmen: FunctionValue<'ctx>,
    pub moo_ui_trenner: FunctionValue<'ctx>,
    pub moo_ui_tabs: FunctionValue<'ctx>,
    pub moo_ui_tab_hinzu: FunctionValue<'ctx>,
    pub moo_ui_tabs_auswahl: FunctionValue<'ctx>,
    pub moo_ui_tabs_auswahl_setze: FunctionValue<'ctx>,
    pub moo_ui_scroll: FunctionValue<'ctx>,
    pub moo_ui_sichtbar: FunctionValue<'ctx>,
    pub moo_ui_aktiv: FunctionValue<'ctx>,
    pub moo_ui_position_setze: FunctionValue<'ctx>,
    pub moo_ui_groesse_setze: FunctionValue<'ctx>,
    pub moo_ui_farbe_setze: FunctionValue<'ctx>,
    pub moo_ui_schrift_setze: FunctionValue<'ctx>,
    pub moo_ui_tooltip_setze: FunctionValue<'ctx>,
    pub moo_ui_zerstoere: FunctionValue<'ctx>,
    pub moo_ui_widget_id_setze: FunctionValue<'ctx>,
    pub moo_ui_widget_id_hole: FunctionValue<'ctx>,
    pub moo_ui_widget_info: FunctionValue<'ctx>,
    pub moo_ui_widget_baum: FunctionValue<'ctx>,
    pub moo_ui_widget_suche: FunctionValue<'ctx>,
    pub moo_ui_test_snapshot: FunctionValue<'ctx>,
    pub moo_ui_test_snapshot_widget: FunctionValue<'ctx>,
    pub moo_ui_test_klick: FunctionValue<'ctx>,
    pub moo_ui_test_klick_xy: FunctionValue<'ctx>,
    pub moo_ui_test_text_setze: FunctionValue<'ctx>,
    pub moo_ui_test_shortcut: FunctionValue<'ctx>,
    pub moo_ui_test_warte: FunctionValue<'ctx>,
    pub moo_ui_test_pump: FunctionValue<'ctx>,
    pub moo_ui_timer_hinzu: FunctionValue<'ctx>,
    pub moo_ui_timer_entfernen: FunctionValue<'ctx>,
    pub moo_ui_info: FunctionValue<'ctx>,
    pub moo_ui_warnung: FunctionValue<'ctx>,
    pub moo_ui_fehler: FunctionValue<'ctx>,
    pub moo_ui_frage: FunctionValue<'ctx>,
    pub moo_ui_eingabe_dialog: FunctionValue<'ctx>,
    pub moo_ui_datei_oeffnen: FunctionValue<'ctx>,
    pub moo_ui_datei_speichern: FunctionValue<'ctx>,
    pub moo_ui_ordner_waehlen: FunctionValue<'ctx>,
    pub moo_ui_menueleiste: FunctionValue<'ctx>,
    pub moo_ui_menue: FunctionValue<'ctx>,
    pub moo_ui_menue_eintrag: FunctionValue<'ctx>,
    pub moo_ui_menue_trenner: FunctionValue<'ctx>,
    pub moo_ui_menue_untermenue: FunctionValue<'ctx>,
    pub moo_ui_shortcut_bind: FunctionValue<'ctx>,
    pub moo_ui_shortcut_loese: FunctionValue<'ctx>,
    // Netzwerk (TCP/UDP)
    pub moo_tcp_server: FunctionValue<'ctx>,
    pub moo_tcp_connect: FunctionValue<'ctx>,
    pub moo_udp_socket: FunctionValue<'ctx>,
    pub moo_udp_connect: FunctionValue<'ctx>,
    pub moo_socket_accept: FunctionValue<'ctx>,
    pub moo_socket_read: FunctionValue<'ctx>,
    pub moo_socket_write: FunctionValue<'ctx>,
    // Profiler
    pub moo_profile_enter: FunctionValue<'ctx>,
    pub moo_profile_exit: FunctionValue<'ctx>,
    pub moo_profile_report: FunctionValue<'ctx>,
    // Eval
    pub moo_eval: FunctionValue<'ctx>,
    // Realtime-Capture (KI-MULTI-C1)
    pub moo_kamera_liste: FunctionValue<'ctx>,
    pub moo_kamera_oeffnen: FunctionValue<'ctx>,
    pub moo_kamera_frame: FunctionValue<'ctx>,
    pub moo_kamera_schliessen: FunctionValue<'ctx>,
    pub moo_mikro_oeffnen: FunctionValue<'ctx>,
    pub moo_mikro_lesen: FunctionValue<'ctx>,
    pub moo_mikro_schliessen: FunctionValue<'ctx>,
    // Webserver
    pub moo_web_server: FunctionValue<'ctx>,
    pub moo_web_accept: FunctionValue<'ctx>,
    pub moo_web_respond: FunctionValue<'ctx>,
    pub moo_web_json: FunctionValue<'ctx>,
    pub moo_web_respond_with_headers: FunctionValue<'ctx>,
    pub moo_web_json_with_headers: FunctionValue<'ctx>,
    pub moo_web_file: FunctionValue<'ctx>,
    pub moo_web_template: FunctionValue<'ctx>,
}

impl<'ctx> RuntimeBindings<'ctx> {
    pub fn declare(context: &'ctx Context, module: &Module<'ctx>) -> Self {
        let ptr_type = context.ptr_type(AddressSpace::default());
        let i32_type = context.i32_type();
        let i8_type = context.i8_type();
        let f64_type = context.f64_type();
        let void_type = context.void_type();
        let bool_type = context.bool_type();

        // MooValue = { uint8_t tag, [7 padding], union { double, ptr } data }
        // C-ABI: sizeof = 16, tag at offset 0, data at offset 8
        // LLVM: { i64, double } passt exakt (8 + 8 = 16 Bytes, korrektes Alignment)
        let i64_type = context.i64_type();
        // MooValue = { uint64_t tag, uint64_t data } — exakt 16 Bytes
        let moo_value_type = context.struct_type(
            &[i64_type.into(), i64_type.into()],
            false,
        );

        let mv: BasicMetadataTypeEnum = moo_value_type.into();
        let mv1 = &[mv];
        let mv2 = &[mv, mv];
        let mv3 = &[mv, mv, mv];
        let mv4 = &[mv, mv, mv, mv];
        let mv5 = &[mv, mv, mv, mv, mv];
        // mv7 = welt + 6 Zahlen (voxel_aabb); mv8 = welt + 7 Zahlen (voxel_strahl).
        let mv7 = &[mv, mv, mv, mv, mv, mv, mv];
        let mv8 = &[mv, mv, mv, mv, mv, mv, mv, mv];

        // Makro fuer Deklaration
        macro_rules! decl {
            ($name:expr, ret $ret:expr, $($params:expr),*) => {
                module.add_function($name, $ret.fn_type(&[$($params.into()),*], false), None)
            };
        }

        // MooValue-returning, N MooValue params
        macro_rules! decl_mv_mv {
            ($name:expr, $params:expr) => {
                module.add_function($name, moo_value_type.fn_type($params, false), None)
            };
        }

        Self {
            moo_value_type,

            // Konstruktoren
            moo_number: decl_mv_mv!("moo_number", &[f64_type.into()]),
            moo_string_new: decl_mv_mv!("moo_string_new", &[ptr_type.into()]),
            moo_bool_fn: decl_mv_mv!("moo_bool", &[bool_type.into()]),
            moo_none: decl_mv_mv!("moo_none", &[]),
            moo_list_new: decl_mv_mv!("moo_list_new", &[i32_type.into()]),
            moo_dict_new: decl_mv_mv!("moo_dict_new", &[]),
            moo_object_new: decl_mv_mv!("moo_object_new", &[ptr_type.into()]),

            // Ops (MooValue, MooValue) -> MooValue
            moo_add: decl_mv_mv!("moo_add", mv2),
            moo_sub: decl_mv_mv!("moo_sub", mv2),
            moo_mul: decl_mv_mv!("moo_mul", mv2),
            moo_div: decl_mv_mv!("moo_div", mv2),
            moo_mod: decl_mv_mv!("moo_mod", mv2),
            moo_pow: decl_mv_mv!("moo_pow", mv2),
            moo_neg: decl_mv_mv!("moo_neg", mv1),
            moo_eq: decl_mv_mv!("moo_eq", mv2),
            moo_neq: decl_mv_mv!("moo_neq", mv2),
            moo_lt: decl_mv_mv!("moo_lt", mv2),
            moo_gt: decl_mv_mv!("moo_gt", mv2),
            moo_lte: decl_mv_mv!("moo_lte", mv2),
            moo_gte: decl_mv_mv!("moo_gte", mv2),
            moo_and: decl_mv_mv!("moo_and", mv2),
            moo_or: decl_mv_mv!("moo_or", mv2),
            moo_not: decl_mv_mv!("moo_not", mv1),

            // Bitwise
            moo_bitand: decl_mv_mv!("moo_bitand", mv2),
            moo_bitor: decl_mv_mv!("moo_bitor", mv2),
            moo_bitxor: decl_mv_mv!("moo_bitxor", mv2),
            moo_bitnot: decl_mv_mv!("moo_bitnot", mv1),
            moo_lshift: decl_mv_mv!("moo_lshift", mv2),
            moo_rshift: decl_mv_mv!("moo_rshift", mv2),
            // Memory
            moo_mem_read: decl_mv_mv!("moo_mem_read", mv2),
            moo_mem_write: module.add_function("moo_mem_write", void_type.fn_type(mv3, false), None),
            // CPU / Hardware
            moo_cpu_halt: module.add_function("moo_cpu_halt", void_type.fn_type(&[], false), None),
            moo_cpu_cli: module.add_function("moo_cpu_cli", void_type.fn_type(&[], false), None),
            moo_cpu_sti: module.add_function("moo_cpu_sti", void_type.fn_type(&[], false), None),
            moo_io_inb: decl_mv_mv!("moo_io_inb", mv1),
            moo_io_outb: module.add_function("moo_io_outb", void_type.fn_type(mv2, false), None),
            // P011-B1: 16/32-bit Port-I/O
            moo_io_inw: decl_mv_mv!("moo_io_inw", mv1),
            moo_io_outw: module.add_function("moo_io_outw", void_type.fn_type(mv2, false), None),
            moo_io_inl: decl_mv_mv!("moo_io_inl", mv1),
            moo_io_outl: module.add_function("moo_io_outl", void_type.fn_type(mv2, false), None),
            // P011-B2: CPU-Steuer-Builtins
            kern_rdmsr_lo: decl_mv_mv!("kern_rdmsr_lo", mv1),
            kern_rdmsr_hi: decl_mv_mv!("kern_rdmsr_hi", mv1),
            kern_wrmsr: module.add_function("kern_wrmsr", void_type.fn_type(mv3, false), None),
            kern_cr_lese: decl_mv_mv!("kern_cr_lese", mv1),
            kern_cr_setze: module.add_function("kern_cr_setze", void_type.fn_type(mv2, false), None),
            kern_lgdt: module.add_function("kern_lgdt", void_type.fn_type(mv2, false), None),
            kern_lidt: module.add_function("kern_lidt", void_type.fn_type(mv2, false), None),

            // Kernel (bare-metal, kern_* — Plan-010). Alle MooValue-returning,
            // damit der Codegen dieselben { i64, i64 }-Calls erzeugt.
            kern_seriell_init: decl_mv_mv!("kern_seriell_init", &[]),
            kern_seriell_zeichen: decl_mv_mv!("kern_seriell_zeichen", mv1),
            kern_seriell_dez: decl_mv_mv!("kern_seriell_dez", mv1),
            kern_seriell_hex: decl_mv_mv!("kern_seriell_hex", mv1),
            kern_vga_init: decl_mv_mv!("kern_vga_init", &[]),
            kern_vga_farbe: decl_mv_mv!("kern_vga_farbe", mv1),
            kern_vga_zeichen: decl_mv_mv!("kern_vga_zeichen", mv1),
            kern_speicher_init: decl_mv_mv!("kern_speicher_init", mv2),
            kern_alloc: decl_mv_mv!("kern_alloc", mv1),
            kern_frei: decl_mv_mv!("kern_frei", mv1),
            kern_speicher_frei: decl_mv_mv!("kern_speicher_frei", &[]),
            kern_speicher_belegt: decl_mv_mv!("kern_speicher_belegt", &[]),
            kern_speicher_peak: decl_mv_mv!("kern_speicher_peak", &[]),
            kern_idt_init: decl_mv_mv!("kern_idt_init", &[]),
            kern_pic_remap: decl_mv_mv!("kern_pic_remap", mv2),
            kern_pic_maskiere: decl_mv_mv!("kern_pic_maskiere", mv1),
            kern_pic_demaskiere: decl_mv_mv!("kern_pic_demaskiere", mv1),
            kern_pic_eoi: decl_mv_mv!("kern_pic_eoi", mv1),
            kern_timer_init: decl_mv_mv!("kern_timer_init", mv1),
            kern_ticks: decl_mv_mv!("kern_ticks", &[]),
            kern_stackprot_selbsttest: decl_mv_mv!("kern_stackprot_selbsttest", &[]),

            // String
            moo_string_concat: decl_mv_mv!("moo_string_concat", mv2),
            // List
            moo_list_append: module.add_function("moo_list_append", void_type.fn_type(mv2, false), None),
            moo_list_length: decl_mv_mv!("moo_list_length", mv1),
            moo_list_pop: decl_mv_mv!("moo_list_pop", mv1),
            moo_list_sort: decl_mv_mv!("moo_list_sort", mv1),
            moo_list_reverse: decl_mv_mv!("moo_list_reverse", mv1),
            moo_list_join: decl_mv_mv!("moo_list_join", mv2),
            moo_list_iter_len: module.add_function("moo_list_iter_len", i32_type.fn_type(mv1, false), None),
            moo_list_iter_get: decl_mv_mv!("moo_list_iter_get", &[mv, i32_type.into()]),

            // Dict
            moo_dict_get: decl_mv_mv!("moo_dict_get", mv2),
            moo_dict_set: module.add_function("moo_dict_set", void_type.fn_type(mv3, false), None),
            moo_dict_has: decl_mv_mv!("moo_dict_has", mv2),
            moo_dict_keys: decl_mv_mv!("moo_dict_keys", mv1),

            // Object
            moo_object_get: decl_mv_mv!("moo_object_get", &[mv, ptr_type.into()]),
            moo_object_set: module.add_function("moo_object_set", void_type.fn_type(&[mv, ptr_type.into(), mv], false), None),
            moo_object_class_name: module.add_function("moo_object_class_name", ptr_type.fn_type(mv1, false), None),
            moo_smart_close: module.add_function("moo_smart_close", void_type.fn_type(mv1, false), None),
            moo_smart_contains: decl_mv_mv!("moo_smart_contains", mv2),
            moo_socket_set_timeout: module.add_function("moo_socket_set_timeout", void_type.fn_type(mv2, false), None),
            moo_socket_read_bytes: decl_mv_mv!("moo_socket_read_bytes", mv2),
            moo_socket_write_bytes: module.add_function("moo_socket_write_bytes", void_type.fn_type(mv2, false), None),
            moo_bytes_to_string: decl_mv_mv!("moo_bytes_to_string", mv1),
            moo_string_to_bytes: decl_mv_mv!("moo_string_to_bytes", mv1),
            // Events
            moo_event_on: module.add_function("moo_event_on", void_type.fn_type(mv3, false), None),
            moo_event_emit: module.add_function("moo_event_emit", void_type.fn_type(mv2, false), None),

            // Print & convert
            moo_print: module.add_function("moo_print", void_type.fn_type(mv1, false), None),
            moo_to_string: decl_mv_mv!("moo_to_string", mv1),

            // Error & truthiness
            moo_throw: module.add_function("moo_throw", void_type.fn_type(mv1, false), None),
            moo_try_enter: module.add_function("moo_try_enter", void_type.fn_type(&[], false), None),
            moo_try_check: module.add_function("moo_try_check", i32_type.fn_type(&[], false), None),
            moo_try_leave: module.add_function("moo_try_leave", void_type.fn_type(&[], false), None),
            moo_get_error: decl_mv_mv!("moo_get_error", &[]),
            moo_is_truthy: module.add_function("moo_is_truthy", bool_type.fn_type(mv1, false), None),
            moo_is_none: module.add_function("moo_is_none", bool_type.fn_type(mv1, false), None),
            // Reference Counting
            moo_retain: module.add_function("moo_retain", void_type.fn_type(mv1, false), None),
            moo_release: module.add_function("moo_release", void_type.fn_type(mv1, false), None),

            // String extras
            moo_string_upper: decl_mv_mv!("moo_string_upper", mv1),
            moo_string_lower: decl_mv_mv!("moo_string_lower", mv1),
            moo_string_trim: decl_mv_mv!("moo_string_trim", mv1),
            moo_string_split: decl_mv_mv!("moo_string_split", mv2),
            moo_string_replace: decl_mv_mv!("moo_string_replace", &[mv, mv, mv]),
            moo_string_contains: decl_mv_mv!("moo_string_contains", mv2),
            moo_string_slice: decl_mv_mv!("moo_string_slice", mv3),
            // Stdlib
            moo_abs: decl_mv_mv!("moo_abs", mv1),
            moo_sqrt: decl_mv_mv!("moo_sqrt", mv1),
            moo_sin: decl_mv_mv!("moo_sin", mv1),
            moo_cos: decl_mv_mv!("moo_cos", mv1),
            moo_tan: decl_mv_mv!("moo_tan", mv1),
            moo_atan2: decl_mv_mv!("moo_atan2", mv2),
            moo_round: decl_mv_mv!("moo_round", mv1),
            moo_floor: decl_mv_mv!("moo_floor", mv1),
            moo_ceil: decl_mv_mv!("moo_ceil", mv1),
            moo_min: decl_mv_mv!("moo_min", mv2),
            moo_max: decl_mv_mv!("moo_max", mv2),
            moo_random: decl_mv_mv!("moo_random", &[]),
            moo_type_of: decl_mv_mv!("moo_type_of", mv1),
            moo_input: decl_mv_mv!("moo_input", mv1),
            moo_length: decl_mv_mv!("moo_length", mv1),
            moo_range: decl_mv_mv!("moo_range", mv2),
            moo_time: decl_mv_mv!("moo_time", &[]),
            moo_time_ms: decl_mv_mv!("moo_time_ms", &[]),
            moo_ki_gpu_statistik: decl_mv_mv!("moo_ki_gpu_statistik", &[]),
            moo_ki_gpu_statistik_reset: decl_mv_mv!("moo_ki_gpu_statistik_reset", &[]),
            moo_syscall: decl_mv_mv!("moo_syscall", &[mv, mv, mv, mv]),
            moo_breakpoint: module.add_function("moo_breakpoint", void_type.fn_type(mv1, false), None),
            moo_index_get: decl_mv_mv!("moo_index_get", mv2),
            moo_index_set: module.add_function("moo_index_set", void_type.fn_type(mv3, false), None),
            // Freeze/Immutable
            moo_freeze: decl_mv_mv!("moo_freeze", mv1),
            moo_is_frozen: decl_mv_mv!("moo_is_frozen", mv1),
            // File I/O
            moo_file_read: decl_mv_mv!("moo_file_read", mv1),
            moo_file_write: decl_mv_mv!("moo_file_write", mv2),
            moo_file_read_bytes: decl_mv_mv!("moo_file_read_bytes", mv1),
            moo_file_write_bytes: decl_mv_mv!("moo_file_write_bytes", mv2),
            moo_file_append: decl_mv_mv!("moo_file_append", mv2),
            moo_file_lines: decl_mv_mv!("moo_file_lines", mv1),
            moo_file_exists: decl_mv_mv!("moo_file_exists", mv1),
            moo_file_delete: decl_mv_mv!("moo_file_delete", mv1),
            moo_file_mtime: decl_mv_mv!("moo_file_mtime", mv1),
            moo_file_is_dir: decl_mv_mv!("moo_file_is_dir", mv1),
            moo_file_mkdir: decl_mv_mv!("moo_file_mkdir", mv1),
            moo_dir_list: decl_mv_mv!("moo_dir_list", mv1),
            // First-Class Funktionen
            // moo_func_new(void* fn_ptr, int32 arity, const char* name) -> MooValue
            moo_func_new: module.add_function("moo_func_new",
                moo_value_type.fn_type(&[ptr_type.into(), i32_type.into(), ptr_type.into()], false),
                None),
            // moo_func_with_captures(void* tramp, int32 arity, const char* name,
            //                        MooValue* caps, int32 n) -> MooValue
            moo_func_with_captures: module.add_function("moo_func_with_captures",
                moo_value_type.fn_type(&[
                    ptr_type.into(), i32_type.into(), ptr_type.into(),
                    ptr_type.into(), i32_type.into(),
                ], false),
                None),
            // moo_func_captured_at(MooFunc* fn, int32 i) -> MooValue
            moo_func_captured_at: module.add_function("moo_func_captured_at",
                moo_value_type.fn_type(&[ptr_type.into(), i32_type.into()], false),
                None),
            moo_func_call_0: decl_mv_mv!("moo_func_call_0", mv1),
            moo_func_call_1: decl_mv_mv!("moo_func_call_1", mv2),
            moo_func_call_2: decl_mv_mv!("moo_func_call_2", mv3),
            moo_func_call_3: decl_mv_mv!("moo_func_call_3", &[mv, mv, mv, mv]),
            moo_func_call_4: decl_mv_mv!("moo_func_call_4", &[mv, mv, mv, mv, mv]),
            moo_func_call_5: decl_mv_mv!("moo_func_call_5", &[mv, mv, mv, mv, mv, mv]),
            moo_func_call_6: decl_mv_mv!("moo_func_call_6", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_func_call_7: decl_mv_mv!("moo_func_call_7", &[mv, mv, mv, mv, mv, mv, mv, mv]),
            moo_func_call_8: decl_mv_mv!("moo_func_call_8", &[mv, mv, mv, mv, mv, mv, mv, mv, mv]),
            // Thread & Channel
            moo_thread_spawn: decl_mv_mv!("moo_thread_spawn", mv2),
            moo_thread_wait: decl_mv_mv!("moo_thread_wait", mv1),
            moo_thread_done: decl_mv_mv!("moo_thread_done", mv1),
            moo_channel_new: decl_mv_mv!("moo_channel_new", mv1),
            moo_channel_send: module.add_function("moo_channel_send", void_type.fn_type(mv2, false), None),
            moo_channel_recv: decl_mv_mv!("moo_channel_recv", mv1),
            // JSON
            moo_json_parse: decl_mv_mv!("moo_json_parse", mv1),
            moo_json_string: decl_mv_mv!("moo_json_string", mv1),
            // HTTP
            moo_http_get: decl_mv_mv!("moo_http_get", mv1),
            moo_http_post: decl_mv_mv!("moo_http_post", mv2),
            moo_http_get_with_headers: decl_mv_mv!("moo_http_get_with_headers", mv2),
            moo_http_post_with_headers: decl_mv_mv!("moo_http_post_with_headers", mv3),
            // Crypto & Security
            moo_sha256: decl_mv_mv!("moo_sha256", mv1),
            moo_sha256_bytes: decl_mv_mv!("moo_sha256_bytes", mv1),
            moo_sha1: decl_mv_mv!("moo_sha1", mv1),
            moo_sha1_bytes: decl_mv_mv!("moo_sha1_bytes", mv1),
            moo_hmac_sha256: decl_mv_mv!("moo_hmac_sha256", mv2),
            moo_pbkdf2_sha256: decl_mv_mv!("moo_pbkdf2_sha256", &[mv, mv, mv, mv]),
            moo_secure_random: decl_mv_mv!("moo_secure_random", mv1),
            // === Tensor (Plan-014 A3) — Tensor-Konvention: Args borrowed,
            // Rueckgabe +1; die Codegen-Arms machen Post-Call-Release. ===
            moo_tensor_neu: decl_mv_mv!("moo_tensor_neu", mv2),
            moo_tensor_nullen: decl_mv_mv!("moo_tensor_nullen", mv1),
            moo_tensor_einsen: decl_mv_mv!("moo_tensor_einsen", mv1),
            moo_tensor_zufall: decl_mv_mv!("moo_tensor_zufall", mv2),
            moo_tensor_aus_liste: decl_mv_mv!("moo_tensor_aus_liste", mv1),
            moo_tensor_holen: decl_mv_mv!("moo_tensor_holen", mv2),
            moo_tensor_setzen: decl_mv_mv!("moo_tensor_setzen", mv3),
            moo_tensor_form: decl_mv_mv!("moo_tensor_form", mv1),
            moo_tensor_groesse: decl_mv_mv!("moo_tensor_groesse", mv1),
            moo_tensor_zu_liste: decl_mv_mv!("moo_tensor_zu_liste", mv1),
            moo_tensor_add: decl_mv_mv!("moo_tensor_add", mv2),
            moo_tensor_sub: decl_mv_mv!("moo_tensor_sub", mv2),
            moo_tensor_mul: decl_mv_mv!("moo_tensor_mul", mv2),
            moo_tensor_div: decl_mv_mv!("moo_tensor_div", mv2),
            moo_tensor_adds: decl_mv_mv!("moo_tensor_adds", mv2),
            moo_tensor_subs: decl_mv_mv!("moo_tensor_subs", mv2),
            moo_tensor_muls: decl_mv_mv!("moo_tensor_muls", mv2),
            moo_tensor_divs: decl_mv_mv!("moo_tensor_divs", mv2),
            moo_tensor_matmul: decl_mv_mv!("moo_tensor_matmul", mv2),
            moo_tensor_transponieren: decl_mv_mv!("moo_tensor_transponieren", mv1),
            moo_tensor_umformen: decl_mv_mv!("moo_tensor_umformen", mv2),
            moo_tensor_zeilen: decl_mv_mv!("moo_tensor_zeilen", mv3),
            moo_tensor_verbinden: decl_mv_mv!("moo_tensor_verbinden", mv2),
            moo_tensor_summe: decl_mv_mv!("moo_tensor_summe", mv2),
            moo_tensor_mittel: decl_mv_mv!("moo_tensor_mittel", mv2),
            moo_tensor_maximum: decl_mv_mv!("moo_tensor_maximum", mv2),
            moo_tensor_exp: decl_mv_mv!("moo_tensor_exp", mv1),
            moo_tensor_log: decl_mv_mv!("moo_tensor_log", mv1),
            moo_tensor_sqrt: decl_mv_mv!("moo_tensor_sqrt", mv1),
            moo_tensor_neg: decl_mv_mv!("moo_tensor_neg", mv1),
            moo_tensor_pow: decl_mv_mv!("moo_tensor_pow", mv2),
            moo_tensor_relu: decl_mv_mv!("moo_tensor_relu", mv1),
            moo_tensor_sigmoid: decl_mv_mv!("moo_tensor_sigmoid", mv1),
            moo_tensor_tanh: decl_mv_mv!("moo_tensor_tanh", mv1),
            moo_tensor_gelu: decl_mv_mv!("moo_tensor_gelu", mv1),
            moo_tensor_softmax: decl_mv_mv!("moo_tensor_softmax", mv1),
            moo_tensor_logsoftmax: decl_mv_mv!("moo_tensor_logsoftmax", mv1),
            moo_tensor_als_dtype: decl_mv_mv!("moo_tensor_als_dtype", mv2),   // D1: (tensor, dtype-string) -> tensor
            // === Autograd (Plan-014 B1) ===
            moo_tensor_mit_gradient: decl_mv_mv!("moo_tensor_mit_gradient", mv1),
            moo_tensor_rueckwaerts: decl_mv_mv!("moo_tensor_rueckwaerts", mv1),
            moo_tensor_gradient: decl_mv_mv!("moo_tensor_gradient", mv1),
            moo_tensor_gradient_loeschen: decl_mv_mv!("moo_tensor_gradient_loeschen", mv1),
            moo_ag_reset: decl_mv_mv!("moo_ag_reset", &[]),
            moo_ag_an: decl_mv_mv!("moo_ag_an", &[]),
            moo_ag_aus: decl_mv_mv!("moo_ag_aus", &[]),
            // === NN (Plan-014 C1) — Tensor-Konvention: Args borrowed,
            // Rueckgabe +1; Codegen-Arms machen Post-Call-Release. ===
            moo_nn_schicht_dicht: decl_mv_mv!("moo_nn_schicht_dicht", &[mv, mv, mv, mv]),
            moo_nn_schicht_faltung: decl_mv_mv!("moo_nn_schicht_faltung", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_nn_schicht_pooling: decl_mv_mv!("moo_nn_schicht_pooling", &[mv, mv, mv]),
            moo_nn_schicht_flach: decl_mv_mv!("moo_nn_schicht_flach", &[]),
            moo_nn_schicht_dropout: decl_mv_mv!("moo_nn_schicht_dropout", mv1),
            moo_nn_schicht_layernorm: decl_mv_mv!("moo_nn_schicht_layernorm", mv1),
            moo_nn_schicht_rmsnorm: decl_mv_mv!("moo_nn_schicht_rmsnorm", mv1),
            moo_nn_schicht_ffn_gated: decl_mv_mv!("moo_nn_schicht_ffn_gated", mv3),
            moo_nn_schicht_embedding: decl_mv_mv!("moo_nn_schicht_embedding", mv3),
            moo_nn_schicht_attention: decl_mv_mv!("moo_nn_schicht_attention", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_nn_schicht_position: decl_mv_mv!("moo_nn_schicht_position", &[mv, mv, mv, mv]),
            moo_nn_schicht_moe: decl_mv_mv!("moo_nn_schicht_moe", mv5),
            moo_nn_moe_balance: decl_mv_mv!("moo_nn_moe_balance", mv1),
            moo_nn_cache_leeren: decl_mv_mv!("moo_nn_cache_leeren", mv1),
            moo_nn_sequence_packen: decl_mv_mv!("moo_nn_sequence_packen", mv2),
            moo_nn_packung_setzen: decl_mv_mv!("moo_nn_packung_setzen", &[mv, mv, mv]),
            moo_nn_packung_leeren: decl_mv_mv!("moo_nn_packung_leeren", mv1),
            moo_nn_vorwaerts: decl_mv_mv!("moo_nn_vorwaerts", mv2),
            moo_nn_parameter: decl_mv_mv!("moo_nn_parameter", mv1),
            moo_nn_mse: decl_mv_mv!("moo_nn_mse", mv2),
            moo_nn_kosinus: decl_mv_mv!("moo_nn_kosinus", mv2),
            moo_nn_kontrastiv: decl_mv_mv!("moo_nn_kontrastiv", &[mv, mv, mv]),
            moo_nn_kreuzentropie: decl_mv_mv!("moo_nn_kreuzentropie", mv2),
            moo_nn_kreuzentropie_maskiert: decl_mv_mv!("moo_nn_kreuzentropie_maskiert", &[mv, mv, mv]),
            moo_nn_opt_sgd: decl_mv_mv!("moo_nn_opt_sgd", mv3),
            moo_nn_opt_adam: decl_mv_mv!("moo_nn_opt_adam", mv2),
            moo_nn_opt_adamw: decl_mv_mv!("moo_nn_opt_adamw", mv3),
            moo_nn_opt_schritt: decl_mv_mv!("moo_nn_opt_schritt", mv1),
            moo_nn_grad_clip: decl_mv_mv!("moo_nn_grad_clip", mv2),
            // Kinderleicht-API (Plan-014 D1)
            moo_nn_ki_netz: decl_mv_mv!("moo_nn_ki_netz", mv1),
            moo_nn_trainiere: decl_mv_mv!("moo_nn_trainiere", &[mv, mv, mv, mv]),
            moo_nn_vorhersage: decl_mv_mv!("moo_nn_vorhersage", mv2),
            moo_nn_genauigkeit: decl_mv_mv!("moo_nn_genauigkeit", mv3),
            moo_nn_speichern: decl_mv_mv!("moo_nn_speichern", mv2),
            moo_nn_laden: decl_mv_mv!("moo_nn_laden", mv1),
            moo_nn_safetensors: decl_mv_mv!("moo_nn_safetensors", mv1),
            // KIP-E2: CPU-Voll-Checkpoint v2 (atomisch, Resume-exakt)
            moo_nn_ckpt_speichern: decl_mv_mv!("moo_nn_ckpt_speichern", mv2),
            moo_nn_ckpt_laden: decl_mv_mv!("moo_nn_ckpt_laden", mv2),
            moo_nn_ckpt_rotieren: decl_mv_mv!("moo_nn_ckpt_rotieren", mv3),
            // Daten-Pipeline (Plan-014 E1)
            moo_ds_mnist: decl_mv_mv!("moo_ds_mnist", mv1),
            moo_ds_csv: decl_mv_mv!("moo_ds_csv", mv1),
            moo_ds_bild: decl_mv_mv!("moo_ds_bild", mv1),
            moo_ds_mischen: decl_mv_mv!("moo_ds_mischen", mv3),
            moo_ds_normalisieren: decl_mv_mv!("moo_ds_normalisieren", mv2),
            moo_ds_tokenizer: decl_mv_mv!("moo_ds_tokenizer", mv1),
            // Byte-level BPE-Tokenizer (KIP-T2). Konvention: Args geliehen,
            // Rueckgabe +1; Codegen-Arms machen Post-Call-Release der Heap-Args.
            moo_tok_trainiere: decl_mv_mv!("moo_tok_trainiere", mv2),
            moo_tok_kodiere: decl_mv_mv!("moo_tok_kodiere", mv2),
            moo_tok_dekodiere: decl_mv_mv!("moo_tok_dekodiere", mv2),
            moo_tok_kodiere_stapel: decl_mv_mv!("moo_tok_kodiere_stapel", mv2),
            moo_tok_speichern: decl_mv_mv!("moo_tok_speichern", mv2),
            moo_tok_laden: decl_mv_mv!("moo_tok_laden", mv1),
            moo_tok_info: decl_mv_mv!("moo_tok_info", mv1),
            moo_tok_hash: decl_mv_mv!("moo_tok_hash", mv1),
            moo_tok_chat_init: decl_mv_mv!("moo_tok_chat_init", mv1),
            moo_tok_spezial_id: decl_mv_mv!("moo_tok_spezial_id", mv2),
            moo_tok_rendern: decl_mv_mv!("moo_tok_rendern", mv3),
            // KIP-E1: Streaming-Token-Shards
            moo_shard_schreiben: decl_mv_mv!("moo_shard_schreiben", mv5),
            moo_shard_info: decl_mv_mv!("moo_shard_info", mv1),
            moo_shard_pruefen: decl_mv_mv!("moo_shard_pruefen", mv1),
            moo_shard_fenster: decl_mv_mv!("moo_shard_fenster", mv3),
            moo_shard_fenster_maske: decl_mv_mv!("moo_shard_fenster_maske", mv3),
            moo_shard_reihenfolge: decl_mv_mv!("moo_shard_reihenfolge", mv3),
            moo_shard_split: decl_mv_mv!("moo_shard_split", mv3),
            moo_base64_encode: decl_mv_mv!("moo_base64_encode", mv1),
            moo_base64_decode: decl_mv_mv!("moo_base64_decode", mv1),
            moo_sanitize_html: decl_mv_mv!("moo_sanitize_html", mv1),
            moo_sanitize_sql: decl_mv_mv!("moo_sanitize_sql", mv1),
            // Database
            moo_db_connect: decl_mv_mv!("moo_db_connect", mv1),
            moo_db_execute: decl_mv_mv!("moo_db_execute", mv2),
            moo_db_query: decl_mv_mv!("moo_db_query", mv2),
            moo_db_close: module.add_function("moo_db_close", void_type.fn_type(mv1, false), None),
            moo_db_execute_with_params: decl_mv_mv!("moo_db_execute_with_params", mv3),
            moo_db_query_with_params: decl_mv_mv!("moo_db_query_with_params", mv3),
            // Hybrid 2D+3D (M5)
            moo_hybrid_create: decl_mv_mv!("moo_hybrid_create", mv3),
            moo_hybrid_is_open: decl_mv_mv!("moo_hybrid_is_open", mv1),
            moo_hybrid_clear: module.add_function("moo_hybrid_clear", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_hybrid_update: module.add_function("moo_hybrid_update", void_type.fn_type(mv1, false), None),
            moo_hybrid_close: module.add_function("moo_hybrid_close", void_type.fn_type(mv1, false), None),
            moo_hybrid_rect_z: module.add_function("moo_hybrid_rect_z", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_hybrid_line_z: module.add_function("moo_hybrid_line_z", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_hybrid_circle_z: module.add_function("moo_hybrid_circle_z", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_hybrid_sprite_z: module.add_function("moo_hybrid_sprite_z", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_hybrid_sprite_load: decl_mv_mv!("moo_hybrid_sprite_load", mv2),
            moo_db_prepare: decl_mv_mv!("moo_db_prepare", mv2),
            moo_db_stmt_bind: decl_mv_mv!("moo_db_stmt_bind", mv3),
            moo_db_stmt_step: decl_mv_mv!("moo_db_stmt_step", mv1),
            moo_db_stmt_execute: decl_mv_mv!("moo_db_stmt_execute", mv1),
            moo_db_stmt_query: decl_mv_mv!("moo_db_stmt_query", mv1),
            moo_db_stmt_reset: decl_mv_mv!("moo_db_stmt_reset", mv1),
            // Result-Typ
            moo_3d_key_pressed: decl_mv_mv!("moo_3d_key_pressed", mv2),
            moo_3d_capture_mouse: module.add_function("moo_3d_capture_mouse", void_type.fn_type(mv1, false), None),
            // Fog + Licht Builtins (raum_licht / raum_umgebungslicht / raum_nebel / raum_nebel_farbe)
            moo_3d_light: module.add_function("moo_3d_light", void_type.fn_type(mv4, false), None),
            moo_3d_ambient: module.add_function("moo_3d_ambient", void_type.fn_type(mv2, false), None),
            moo_3d_fog: module.add_function("moo_3d_fog", void_type.fn_type(mv2, false), None),
            moo_3d_fog_color: module.add_function("moo_3d_fog_color", void_type.fn_type(mv2, false), None),
            moo_3d_sky: module.add_function("moo_3d_sky", void_type.fn_type(mv3, false), None),
            // Gouraud-Dreieck: win + 9 Koordinaten + 3 Farben = 13 MooValues
            moo_3d_triangle_colors: module.add_function("moo_3d_triangle_colors", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_3d_alpha: module.add_function("moo_3d_alpha", void_type.fn_type(mv2, false), None),
            moo_3d_wave: module.add_function("moo_3d_wave", void_type.fn_type(mv4, false), None),
            moo_3d_light_color: module.add_function("moo_3d_light_color", void_type.fn_type(mv2, false), None),
            moo_3d_spec: module.add_function("moo_3d_spec", void_type.fn_type(mv3, false), None),
            moo_3d_clear_hex: module.add_function("moo_3d_clear_hex", void_type.fn_type(mv2, false), None),
            moo_3d_time_of_day: decl_mv_mv!("moo_3d_time_of_day", mv2),
            moo_3d_release_mouse: module.add_function("moo_3d_release_mouse", void_type.fn_type(mv1, false), None),
            moo_3d_mouse_dx: decl_mv_mv!("moo_3d_mouse_dx", mv1),
            moo_3d_mouse_dy: decl_mv_mv!("moo_3d_mouse_dy", mv1),

            // Voxel-Welt (Plan-005 Phase 1a). Signaturen exakt nach RT1-C-API
            // (moo_runtime.h): alle MooValue-in/MooValue-out.
            moo_voxel_welt_neu: decl_mv_mv!("moo_voxel_welt_neu", mv1),
            //   moo_voxel_generieren(welt, cx, cz) -> Number (neue Chunks)  (3 Args = mv3)
            moo_voxel_generieren: decl_mv_mv!("moo_voxel_generieren", mv3),
            moo_voxel_setzen: decl_mv_mv!("moo_voxel_setzen", mv5),
            moo_voxel_holen: decl_mv_mv!("moo_voxel_holen", mv4),
            moo_voxel_ram_statistik: decl_mv_mv!("moo_voxel_ram_statistik", mv1),
            //   moo_voxel_welt_optimieren(welt) -> Number (geaenderte Chunks)  (1 Arg = mv1)
            moo_voxel_welt_optimieren: decl_mv_mv!("moo_voxel_welt_optimieren", mv1),
            // Voxel-Mesher (Plan-005 Phase 1b, CG2 nach RT2). Signaturen exakt
            // nach RT2-C-API (moo_runtime.h): alle MooValue-in/MooValue-out.
            //   moo_voxel_mesh_bauen(welt, cx, cy, cz) -> Number  (4 Args = mv4)
            //   moo_voxel_aktualisieren(welt)          -> Number  (1 Arg  = mv1)
            moo_voxel_mesh_bauen: decl_mv_mv!("moo_voxel_mesh_bauen", mv4),
            moo_voxel_aktualisieren: decl_mv_mv!("moo_voxel_aktualisieren", mv1),
            // Voxel-Raycast/AABB (Plan-005 Phase 1d, CG3 nach RT4). Signaturen exakt
            // nach RT4-C-API (moo_runtime.h, P0.5-Contract): alle MooValue-in/MooValue-out.
            //   moo_voxel_strahl(welt, ox,oy,oz, dx,dy,dz, max_dist) -> Dict  (8 Args = mv8)
            //   moo_voxel_aabb(welt, minx,miny,minz, maxx,maxy,maxz)  -> Dict  (7 Args = mv7)
            moo_voxel_strahl: decl_mv_mv!("moo_voxel_strahl", mv8),
            moo_voxel_aabb: decl_mv_mv!("moo_voxel_aabb", mv7),
            moo_3d_mouse_x: decl_mv_mv!("moo_3d_mouse_x", mv1),
            moo_3d_mouse_y: decl_mv_mv!("moo_3d_mouse_y", mv1),
            moo_3d_mouse_button: decl_mv_mv!("moo_3d_mouse_button", mv2),
            moo_3d_mouse_wheel: decl_mv_mv!("moo_3d_mouse_wheel", mv1),
            moo_3d_simulate_mouse_pos: module.add_function("moo_3d_simulate_mouse_pos", void_type.fn_type(mv3, false), None),
            moo_3d_simulate_mouse_button: module.add_function("moo_3d_simulate_mouse_button", void_type.fn_type(mv3, false), None),
            moo_3d_simulate_scroll: module.add_function("moo_3d_simulate_scroll", void_type.fn_type(mv2, false), None),
            moo_3d_simulate_key: module.add_function("moo_3d_simulate_key", void_type.fn_type(mv3, false), None),
            moo_3d_simulate_mouse_delta: module.add_function("moo_3d_simulate_mouse_delta", void_type.fn_type(mv3, false), None),
            moo_3d_simulate_reset: module.add_function("moo_3d_simulate_reset", void_type.fn_type(mv1, false), None),
            moo_3d_screenshot_bmp: decl_mv_mv!("moo_3d_screenshot_bmp", mv2),
            // Einheitlicher Test-API-Layer (Plan-008 A2). Symbole immer deklariert;
            // C-seitig nur in 3D-Builds gelinkt (moo_test_api.c, build.rs).
            moo_test_sim_taste: module.add_function("moo_test_sim_taste", void_type.fn_type(mv3, false), None),
            moo_test_sim_maus_pos: module.add_function("moo_test_sim_maus_pos", void_type.fn_type(mv3, false), None),
            moo_test_sim_maus_taste: module.add_function("moo_test_sim_maus_taste", void_type.fn_type(mv3, false), None),
            moo_test_sim_maus_rad: module.add_function("moo_test_sim_maus_rad", void_type.fn_type(mv2, false), None),
            moo_test_sim_maus_delta: module.add_function("moo_test_sim_maus_delta", void_type.fn_type(mv3, false), None),
            moo_test_sim_reset: module.add_function("moo_test_sim_reset", void_type.fn_type(mv1, false), None),
            moo_test_screenshot: decl_mv_mv!("moo_test_screenshot", mv2),
            moo_test_fenster_info: decl_mv_mv!("moo_test_fenster_info", mv1),
            // Frame-Grab / Pixel (Plan-008 A3A, opaker MOO_FRAME-Heap-Typ).
            //   moo_test_frame_grab(win)            -> MOO_FRAME (1 Arg = mv1)
            //   moo_test_pixel(frame_oder_win,x,y)  -> Dict      (3 Args = mv3)
            //   moo_test_frame_save_bmp(frame,pfad) -> Bool      (2 Args = mv2)
            moo_test_frame_grab: decl_mv_mv!("moo_test_frame_grab", mv1),
            moo_test_pixel: decl_mv_mv!("moo_test_pixel", mv3),
            moo_test_frame_save_bmp: decl_mv_mv!("moo_test_frame_save_bmp", mv2),
            // 2D-Debug-Erweiterungen (6bb03790 B):
            //   moo_test_frame_diff(a, b)               -> Dict {maxdiff,geaenderte_pixel,prozent}
            //   moo_test_frame_region(f, x, y, b, h)    -> Dict {rot,gruen,blau,alpha} (Durchschnitt)
            //   moo_test_frame_save_png(frame, pfad)    -> Bool (SDL2_image, Grafik-Build)
            moo_test_frame_diff: decl_mv_mv!("moo_test_frame_diff", mv2),
            moo_test_frame_region: decl_mv_mv!("moo_test_frame_region", mv5),
            moo_test_frame_save_png: decl_mv_mv!("moo_test_frame_save_png", mv2),
            // Frame<->Tensor-Bruecke (KI-MULTI-V1, moo_frame_tensor.c, immer gebaut):
            //   moo_tensor_aus_frame(frame, modus?)  -> Tensor [h,b,4] / [h,b,1] (2 Args = mv2)
            //   moo_frame_aus_tensor(t)              -> MOO_FRAME             (1 Arg  = mv1)
            moo_tensor_aus_frame: decl_mv_mv!("moo_tensor_aus_frame", mv2),
            moo_frame_aus_tensor: decl_mv_mv!("moo_frame_aus_tensor", mv1),
            // Audio-Features (KI-MULTI-A1): FFT/Betrag/WAV = mv1, STFT = mv3.
            moo_fft: decl_mv_mv!("moo_fft", mv1),
            moo_spektrum_betrag: decl_mv_mv!("moo_spektrum_betrag", mv1),
            moo_spektrogramm: decl_mv_mv!("moo_spektrogramm", mv3),
            moo_wav_lesen: decl_mv_mv!("moo_wav_lesen", mv1),
            // GIF-Recorder (Plan-008 A3B). Symbole immer deklariert; C-seitig
            // in moo_test_api.c (3D-Build) gelinkt. Encoder-Kern (moo_gif.c)
            // ist Core-Build, daher immer verfuegbar.
            //   moo_test_gif_start(win_oder_frame, pfad, fps) -> MOO_GIF (3 Args = mv3)
            //   moo_test_gif_frame(gif, frame_oder_win)        -> Bool    (2 Args = mv2)
            //   moo_test_gif_ende(gif)                         -> Bool    (1 Arg  = mv1)
            moo_test_gif_start: decl_mv_mv!("moo_test_gif_start", mv3),
            moo_test_gif_frame: decl_mv_mv!("moo_test_gif_frame", mv2),
            moo_test_gif_ende: decl_mv_mv!("moo_test_gif_ende", mv1),
            // MP4-Video-Recorder (Plan-009 V1). Encoder-Kern (moo_video.c) +
            // Heap-Wrapper (moo_video_handle.c) sind Core-Build, immer verfuegbar.
            //   moo_test_video_start(win_oder_frame, pfad, fps) -> MOO_VIDEO (3 Args = mv3)
            //   moo_test_video_frame(video, frame_oder_win)      -> Bool      (2 Args = mv2)
            //   moo_test_video_ende(video)                       -> Bool      (1 Arg  = mv1)
            moo_test_video_start: decl_mv_mv!("moo_test_video_start", mv3),
            moo_test_video_frame: decl_mv_mv!("moo_test_video_frame", mv2),
            moo_test_video_ende: decl_mv_mv!("moo_test_video_ende", mv1),
            // Chunk Display Lists
            moo_3d_chunk_create: decl_mv_mv!("moo_3d_chunk_create", &[]),
            moo_3d_chunk_begin: module.add_function("moo_3d_chunk_begin", void_type.fn_type(mv1, false), None),
            moo_3d_chunk_end: module.add_function("moo_3d_chunk_end", void_type.fn_type(&[], false), None),
            moo_3d_chunk_draw: module.add_function("moo_3d_chunk_draw", void_type.fn_type(mv1, false), None),
            moo_3d_chunk_delete: module.add_function("moo_3d_chunk_delete", void_type.fn_type(mv1, false), None),
            // Welt (Game-Dev Runtime)
            moo_world_create: decl_mv_mv!("moo_world_create", mv3),
            moo_world_is_open: decl_mv_mv!("moo_world_is_open", mv1),
            moo_world_update: module.add_function("moo_world_update", void_type.fn_type(mv1, false), None),
            moo_world_close: module.add_function("moo_world_close", void_type.fn_type(mv1, false), None),
            moo_world_seed: module.add_function("moo_world_seed", void_type.fn_type(mv2, false), None),
            moo_world_biome: module.add_function("moo_world_biome", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_world_trees: module.add_function("moo_world_trees", void_type.fn_type(mv3, false), None),
            moo_world_sun: module.add_function("moo_world_sun", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_world_fog: module.add_function("moo_world_fog", void_type.fn_type(mv2, false), None),
            moo_world_sea_level: module.add_function("moo_world_sea_level", void_type.fn_type(mv2, false), None),
            moo_world_render_dist: module.add_function("moo_world_render_dist", void_type.fn_type(mv2, false), None),
            moo_world_height_at: decl_mv_mv!("moo_world_height_at", mv3),
            moo_world_time_of_day: module.add_function("moo_world_time_of_day", void_type.fn_type(mv2, false), None),
            // Test-API
            moo_screenshot: decl_mv_mv!("moo_screenshot", mv2),
            moo_simulate_key: module.add_function("moo_simulate_key", void_type.fn_type(mv2, false), None),
            moo_simulate_mouse: module.add_function("moo_simulate_mouse", void_type.fn_type(mv3, false), None),
            // Sprites
            moo_sprite_load: decl_mv_mv!("moo_sprite_load", mv2),
            moo_sprite_draw: module.add_function("moo_sprite_draw", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_sprite_draw_scaled: module.add_function("moo_sprite_draw_scaled", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_sprite_draw_region: module.add_function("moo_sprite_draw_region", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_sprite_width: decl_mv_mv!("moo_sprite_width", mv1),
            moo_sprite_height: decl_mv_mv!("moo_sprite_height", mv1),
            moo_sprite_free: module.add_function("moo_sprite_free", void_type.fn_type(mv1, false), None),
            moo_result_ok: decl_mv_mv!("moo_result_ok", mv1),
            moo_result_err: decl_mv_mv!("moo_result_err", mv1),
            moo_result_is_ok: decl_mv_mv!("moo_result_is_ok", mv1),
            moo_result_is_err: decl_mv_mv!("moo_result_is_err", mv1),
            moo_result_unwrap: decl_mv_mv!("moo_result_unwrap", mv1),
            // Grafik (SDL2)
            moo_window_create: decl_mv_mv!("moo_window_create", mv3),
            moo_window_clear: module.add_function("moo_window_clear", void_type.fn_type(mv2, false), None),
            moo_window_update: module.add_function("moo_window_update", void_type.fn_type(mv1, false), None),
            moo_window_is_open: decl_mv_mv!("moo_window_is_open", mv1),
            moo_window_close: module.add_function("moo_window_close", void_type.fn_type(mv1, false), None),
            moo_draw_rect: module.add_function("moo_draw_rect", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_draw_circle: module.add_function("moo_draw_circle", void_type.fn_type(&[mv, mv, mv, mv, mv], false), None),
            moo_draw_line: module.add_function("moo_draw_line", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_draw_pixel: module.add_function("moo_draw_pixel", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            // Grafik Input (SDL2)
            moo_key_pressed: decl_mv_mv!("moo_key_pressed", mv1),
            moo_mouse_x: decl_mv_mv!("moo_mouse_x", mv1),
            moo_mouse_y: decl_mv_mv!("moo_mouse_y", mv1),
            moo_mouse_pressed: decl_mv_mv!("moo_mouse_pressed", mv1),
            moo_delay: module.add_function("moo_delay", void_type.fn_type(mv1, false), None),
            moo_pump_events: module.add_function("moo_pump_events", void_type.fn_type(&[], false), None),
            // 3D Grafik
            moo_3d_create: decl_mv_mv!("moo_3d_create", mv3),
            moo_3d_is_open: decl_mv_mv!("moo_3d_is_open", mv1),
            moo_3d_clear: module.add_function("moo_3d_clear", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_3d_update: module.add_function("moo_3d_update", void_type.fn_type(mv1, false), None),
            moo_3d_close: module.add_function("moo_3d_close", void_type.fn_type(mv1, false), None),
            moo_3d_perspective: module.add_function("moo_3d_perspective", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_3d_camera: module.add_function("moo_3d_camera", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_3d_rotate: module.add_function("moo_3d_rotate", void_type.fn_type(&[mv, mv, mv, mv, mv], false), None),
            moo_3d_translate: module.add_function("moo_3d_translate", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_3d_push: module.add_function("moo_3d_push", void_type.fn_type(mv1, false), None),
            moo_3d_pop: module.add_function("moo_3d_pop", void_type.fn_type(mv1, false), None),
            moo_3d_triangle: module.add_function("moo_3d_triangle", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_3d_cube: module.add_function("moo_3d_cube", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_3d_sphere: module.add_function("moo_3d_sphere", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            // Regex
            moo_regex_new: decl_mv_mv!("moo_regex_new", mv1),
            moo_regex_match: decl_mv_mv!("moo_regex_match", mv2),
            moo_regex_find: decl_mv_mv!("moo_regex_find", mv2),
            moo_regex_find_all: decl_mv_mv!("moo_regex_find_all", mv2),
            moo_regex_replace: decl_mv_mv!("moo_regex_replace", mv3),
            // Kern-Builtins
            moo_sleep: module.add_function("moo_sleep", void_type.fn_type(mv1, false), None),
            moo_env: decl_mv_mv!("moo_env", mv1),
            moo_exit: module.add_function("moo_exit", void_type.fn_type(mv1, false), None),
            moo_to_number: decl_mv_mv!("moo_to_number", mv1),
            moo_args: decl_mv_mv!("moo_args", &[]),
            moo_pid: decl_mv_mv!("moo_pid", &[]),
            // Tray (erweitert — moo_tray.h)
            moo_tray_create: decl_mv_mv!("moo_tray_create", mv2),
            moo_tray_titel_setze: decl_mv_mv!("moo_tray_titel_setze", mv2),
            moo_tray_icon_setze: decl_mv_mv!("moo_tray_icon_setze", mv2),
            moo_tray_aktiv: decl_mv_mv!("moo_tray_aktiv", mv2),
            moo_tray_menu_add: decl_mv_mv!("moo_tray_menu_add", mv3),
            moo_tray_separator_add: decl_mv_mv!("moo_tray_separator_add", mv1),
            moo_tray_menu_clear: decl_mv_mv!("moo_tray_menu_clear", mv1),
            moo_tray_submenu_add: decl_mv_mv!("moo_tray_submenu_add", mv2),
            moo_tray_menu_add_to: decl_mv_mv!("moo_tray_menu_add_to", mv3),
            moo_tray_separator_add_to: decl_mv_mv!("moo_tray_separator_add_to", mv1),
            moo_tray_check_add: decl_mv_mv!("moo_tray_check_add", &[mv, mv, mv, mv]),
            moo_tray_check_add_to: decl_mv_mv!("moo_tray_check_add_to", &[mv, mv, mv, mv]),
            moo_tray_check_wert: decl_mv_mv!("moo_tray_check_wert", mv1),
            moo_tray_check_set: decl_mv_mv!("moo_tray_check_set", mv2),
            moo_tray_item_aktiv: decl_mv_mv!("moo_tray_item_aktiv", mv2),
            moo_tray_item_label_setze: decl_mv_mv!("moo_tray_item_label_setze", mv2),
            moo_tray_timer_add: decl_mv_mv!("moo_tray_timer_add", mv2),
            moo_tray_timer_remove: decl_mv_mv!("moo_tray_timer_remove", mv1),
            moo_tray_run: decl_mv_mv!("moo_tray_run", &[]),
            // UI (Cross-Platform — moo_ui.h)
            moo_ui_init: decl_mv_mv!("moo_ui_init", &[]),
            moo_ui_laufen: decl_mv_mv!("moo_ui_laufen", &[]),
            moo_ui_beenden: decl_mv_mv!("moo_ui_beenden", &[]),
            moo_ui_pump: decl_mv_mv!("moo_ui_pump", &[]),
            moo_ui_debug: decl_mv_mv!("moo_ui_debug", mv1),
            moo_ui_fenster: decl_mv_mv!("moo_ui_fenster", &[mv, mv, mv, mv, mv]),
            moo_ui_fenster_titel_setze: decl_mv_mv!("moo_ui_fenster_titel_setze", mv2),
            moo_ui_fenster_icon_setze: decl_mv_mv!("moo_ui_fenster_icon_setze", mv2),
            moo_ui_fenster_groesse_setze: decl_mv_mv!("moo_ui_fenster_groesse_setze", mv3),
            moo_ui_fenster_position_setze: decl_mv_mv!("moo_ui_fenster_position_setze", mv3),
            moo_ui_fenster_schliessen: decl_mv_mv!("moo_ui_fenster_schliessen", mv1),
            moo_ui_zeige: decl_mv_mv!("moo_ui_zeige", mv1),
            moo_ui_zeige_nebenbei: decl_mv_mv!("moo_ui_zeige_nebenbei", mv1),
            moo_ui_fenster_on_close: decl_mv_mv!("moo_ui_fenster_on_close", mv2),
            moo_ui_fenster_on_resize: decl_mv_mv!("moo_ui_fenster_on_resize", mv2),
            moo_ui_label: decl_mv_mv!("moo_ui_label", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_label_setze: decl_mv_mv!("moo_ui_label_setze", mv2),
            moo_ui_label_text: decl_mv_mv!("moo_ui_label_text", mv1),
            moo_ui_knopf: decl_mv_mv!("moo_ui_knopf", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_checkbox: decl_mv_mv!("moo_ui_checkbox", &[mv, mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_checkbox_wert: decl_mv_mv!("moo_ui_checkbox_wert", mv1),
            moo_ui_checkbox_setze: decl_mv_mv!("moo_ui_checkbox_setze", mv2),
            moo_ui_radio: decl_mv_mv!("moo_ui_radio", &[mv, mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_radio_wert: decl_mv_mv!("moo_ui_radio_wert", mv1),
            moo_ui_eingabe: decl_mv_mv!("moo_ui_eingabe", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_eingabe_text: decl_mv_mv!("moo_ui_eingabe_text", mv1),
            moo_ui_eingabe_setze: decl_mv_mv!("moo_ui_eingabe_setze", mv2),
            moo_ui_eingabe_on_change: decl_mv_mv!("moo_ui_eingabe_on_change", mv2),
            moo_ui_eingabe_on_enter: decl_mv_mv!("moo_ui_eingabe_on_enter", mv2),
            moo_ui_textbereich: decl_mv_mv!("moo_ui_textbereich", &[mv, mv, mv, mv, mv]),
            moo_ui_textbereich_text: decl_mv_mv!("moo_ui_textbereich_text", mv1),
            moo_ui_textbereich_setze: decl_mv_mv!("moo_ui_textbereich_setze", mv2),
            moo_ui_textbereich_anhaengen: decl_mv_mv!("moo_ui_textbereich_anhaengen", mv2),
            moo_ui_textbereich_on_key: decl_mv_mv!("moo_ui_textbereich_on_key", mv2),
            moo_ui_textbereich_zeile_anzahl: decl_mv_mv!("moo_ui_textbereich_zeile_anzahl", mv1),
            moo_ui_dropdown: decl_mv_mv!("moo_ui_dropdown", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_dropdown_auswahl: decl_mv_mv!("moo_ui_dropdown_auswahl", mv1),
            moo_ui_dropdown_auswahl_setze: decl_mv_mv!("moo_ui_dropdown_auswahl_setze", mv2),
            moo_ui_dropdown_text: decl_mv_mv!("moo_ui_dropdown_text", mv1),
            moo_ui_liste: decl_mv_mv!("moo_ui_liste", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_liste_zeile_hinzu: decl_mv_mv!("moo_ui_liste_zeile_hinzu", mv2),
            moo_ui_liste_zeilen_hinzu_bulk: decl_mv_mv!("moo_ui_liste_zeilen_hinzu_bulk", mv2),
            moo_ui_liste_auswahl: decl_mv_mv!("moo_ui_liste_auswahl", mv1),
            moo_ui_liste_zeile: decl_mv_mv!("moo_ui_liste_zeile", mv2),
            moo_ui_liste_leeren: decl_mv_mv!("moo_ui_liste_leeren", mv1),
            moo_ui_liste_on_auswahl: decl_mv_mv!("moo_ui_liste_on_auswahl", mv2),
            moo_ui_liste_on_scroll: decl_mv_mv!("moo_ui_liste_on_scroll", mv2),
            moo_ui_liste_scroll_zu: decl_mv_mv!("moo_ui_liste_scroll_zu", mv2),
            moo_ui_liste_scroll_unten: decl_mv_mv!("moo_ui_liste_scroll_unten", mv1),
            moo_ui_liste_spalte_breite: decl_mv_mv!("moo_ui_liste_spalte_breite", mv3),
            moo_ui_liste_spalte_min_breite: decl_mv_mv!("moo_ui_liste_spalte_min_breite", mv3),
            moo_ui_liste_spalten_autosize: decl_mv_mv!("moo_ui_liste_spalten_autosize", mv1),
            moo_ui_liste_spalte_breite_lese: decl_mv_mv!("moo_ui_liste_spalte_breite_lese", mv2),
            moo_ui_liste_ist_unten: decl_mv_mv!("moo_ui_liste_ist_unten", mv1),
            moo_ui_liste_on_rechtsklick: decl_mv_mv!("moo_ui_liste_on_rechtsklick", mv2),
            moo_ui_clipboard_setze: decl_mv_mv!("moo_ui_clipboard_setze", mv1),
            moo_ui_menue_eintrag_data: decl_mv_mv!("moo_ui_menue_eintrag_data", mv2),
            moo_ui_menue_eintrag_lookup: decl_mv_mv!("moo_ui_menue_eintrag_lookup", mv1),
            moo_ui_menue_eintrag_aktiv: decl_mv_mv!("moo_ui_menue_eintrag_aktiv", &[]),
            moo_ui_zeit_jetzt: decl_mv_mv!("moo_ui_zeit_jetzt", &[]),
            moo_ui_zeit_lokal: decl_mv_mv!("moo_ui_zeit_lokal", mv1),
            moo_ui_zeit_format: decl_mv_mv!("moo_ui_zeit_format", mv2),
            moo_ui_liste_sortierbar: decl_mv_mv!("moo_ui_liste_sortierbar", mv3),
            moo_ui_liste_sortiere: decl_mv_mv!("moo_ui_liste_sortiere", mv3),
            moo_ui_liste_zeile_setze: decl_mv_mv!("moo_ui_liste_zeile_setze", mv3),
            moo_ui_liste_zelle_setze: decl_mv_mv!("moo_ui_liste_zelle_setze", &[mv, mv, mv, mv]),
            moo_ui_liste_entferne: decl_mv_mv!("moo_ui_liste_entferne", mv2),
            moo_ui_slider: decl_mv_mv!("moo_ui_slider", &[mv, mv, mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_slider_wert: decl_mv_mv!("moo_ui_slider_wert", mv1),
            moo_ui_slider_setze: decl_mv_mv!("moo_ui_slider_setze", mv2),
            moo_ui_fortschritt: decl_mv_mv!("moo_ui_fortschritt", &[mv, mv, mv, mv, mv]),
            moo_ui_fortschritt_setze: decl_mv_mv!("moo_ui_fortschritt_setze", mv2),
            moo_ui_bild: decl_mv_mv!("moo_ui_bild", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_bild_setze: decl_mv_mv!("moo_ui_bild_setze", mv2),
            moo_ui_leinwand: decl_mv_mv!("moo_ui_leinwand", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_leinwand_anfordern: decl_mv_mv!("moo_ui_leinwand_anfordern", mv1),
            moo_ui_leinwand_on_maus: decl_mv_mv!("moo_ui_leinwand_on_maus", mv2),
            moo_ui_leinwand_on_bewegung: decl_mv_mv!("moo_ui_leinwand_on_bewegung", mv2),
            moo_ui_zeichne_farbe: decl_mv_mv!("moo_ui_zeichne_farbe", &[mv, mv, mv, mv, mv]),
            moo_ui_zeichne_linie: decl_mv_mv!("moo_ui_zeichne_linie", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_zeichne_rechteck: decl_mv_mv!("moo_ui_zeichne_rechteck", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_zeichne_kreis: decl_mv_mv!("moo_ui_zeichne_kreis", &[mv, mv, mv, mv, mv]),
            moo_ui_zeichne_text: decl_mv_mv!("moo_ui_zeichne_text", &[mv, mv, mv, mv, mv]),
            moo_ui_zeichne_text_breite: decl_mv_mv!("moo_ui_zeichne_text_breite", mv3),
            moo_ui_zeichne_bild: decl_mv_mv!("moo_ui_zeichne_bild", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_rahmen: decl_mv_mv!("moo_ui_rahmen", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_trenner: decl_mv_mv!("moo_ui_trenner", &[mv, mv, mv, mv, mv]),
            moo_ui_tabs: decl_mv_mv!("moo_ui_tabs", &[mv, mv, mv, mv, mv]),
            moo_ui_tab_hinzu: decl_mv_mv!("moo_ui_tab_hinzu", mv2),
            moo_ui_tabs_auswahl: decl_mv_mv!("moo_ui_tabs_auswahl", mv1),
            moo_ui_tabs_auswahl_setze: decl_mv_mv!("moo_ui_tabs_auswahl_setze", mv2),
            moo_ui_scroll: decl_mv_mv!("moo_ui_scroll", &[mv, mv, mv, mv, mv]),
            moo_ui_sichtbar: decl_mv_mv!("moo_ui_sichtbar", mv2),
            moo_ui_aktiv: decl_mv_mv!("moo_ui_aktiv", mv2),
            moo_ui_position_setze: decl_mv_mv!("moo_ui_position_setze", mv3),
            moo_ui_groesse_setze: decl_mv_mv!("moo_ui_groesse_setze", mv3),
            moo_ui_farbe_setze: decl_mv_mv!("moo_ui_farbe_setze", mv2),
            moo_ui_schrift_setze: decl_mv_mv!("moo_ui_schrift_setze", mv3),
            moo_ui_tooltip_setze: decl_mv_mv!("moo_ui_tooltip_setze", mv2),
            moo_ui_zerstoere: decl_mv_mv!("moo_ui_zerstoere", mv1),
            moo_ui_widget_id_setze: decl_mv_mv!("moo_ui_widget_id_setze", mv2),
            moo_ui_widget_id_hole: decl_mv_mv!("moo_ui_widget_id_hole", mv1),
            moo_ui_widget_info: decl_mv_mv!("moo_ui_widget_info", mv1),
            moo_ui_widget_baum: decl_mv_mv!("moo_ui_widget_baum", mv1),
            moo_ui_widget_suche: decl_mv_mv!("moo_ui_widget_suche", mv2),
            moo_ui_test_snapshot: decl_mv_mv!("moo_ui_test_snapshot", mv2),
            moo_ui_test_snapshot_widget: decl_mv_mv!("moo_ui_test_snapshot_widget", mv2),
            moo_ui_test_klick: decl_mv_mv!("moo_ui_test_klick", mv1),
            moo_ui_test_klick_xy: decl_mv_mv!("moo_ui_test_klick_xy", mv3),
            moo_ui_test_text_setze: decl_mv_mv!("moo_ui_test_text_setze", mv2),
            moo_ui_test_shortcut: decl_mv_mv!("moo_ui_test_shortcut", mv2),
            moo_ui_test_warte: decl_mv_mv!("moo_ui_test_warte", mv1),
            moo_ui_test_pump: decl_mv_mv!("moo_ui_test_pump", &[]),
            moo_ui_timer_hinzu: decl_mv_mv!("moo_ui_timer_hinzu", mv2),
            moo_ui_timer_entfernen: decl_mv_mv!("moo_ui_timer_entfernen", mv1),
            moo_ui_info: decl_mv_mv!("moo_ui_info", mv3),
            moo_ui_warnung: decl_mv_mv!("moo_ui_warnung", mv3),
            moo_ui_fehler: decl_mv_mv!("moo_ui_fehler", mv3),
            moo_ui_frage: decl_mv_mv!("moo_ui_frage", mv3),
            moo_ui_eingabe_dialog: decl_mv_mv!("moo_ui_eingabe_dialog", &[mv, mv, mv, mv]),
            moo_ui_datei_oeffnen: decl_mv_mv!("moo_ui_datei_oeffnen", mv3),
            moo_ui_datei_speichern: decl_mv_mv!("moo_ui_datei_speichern", mv3),
            moo_ui_ordner_waehlen: decl_mv_mv!("moo_ui_ordner_waehlen", mv2),
            moo_ui_menueleiste: decl_mv_mv!("moo_ui_menueleiste", mv1),
            moo_ui_menue: decl_mv_mv!("moo_ui_menue", mv2),
            moo_ui_menue_eintrag: decl_mv_mv!("moo_ui_menue_eintrag", mv3),
            moo_ui_menue_trenner: decl_mv_mv!("moo_ui_menue_trenner", mv1),
            moo_ui_menue_untermenue: decl_mv_mv!("moo_ui_menue_untermenue", mv2),
            moo_ui_shortcut_bind: decl_mv_mv!("moo_ui_shortcut_bind", mv3),
            moo_ui_shortcut_loese: decl_mv_mv!("moo_ui_shortcut_loese", mv2),
            // Netzwerk
            moo_tcp_server: decl_mv_mv!("moo_tcp_server", mv1),
            moo_tcp_connect: decl_mv_mv!("moo_tcp_connect", mv2),
            moo_udp_socket: decl_mv_mv!("moo_udp_socket", mv1),
            moo_udp_connect: module.add_function("moo_udp_connect", void_type.fn_type(mv3, false), None),
            moo_socket_accept: decl_mv_mv!("moo_socket_accept", mv1),
            moo_socket_read: decl_mv_mv!("moo_socket_read", mv2),
            moo_socket_write: module.add_function("moo_socket_write", void_type.fn_type(mv2, false), None),
            // Profiler
            moo_profile_enter: module.add_function("moo_profile_enter", void_type.fn_type(mv1, false), None),
            moo_profile_exit: module.add_function("moo_profile_exit", void_type.fn_type(mv1, false), None),
            moo_profile_report: module.add_function("moo_profile_report", void_type.fn_type(&[], false), None),
            // Eval
            moo_eval: decl_mv_mv!("moo_eval", mv1),
            // Realtime-Capture
            moo_kamera_liste: decl_mv_mv!("moo_kamera_liste", &[]),
            moo_kamera_oeffnen: decl_mv_mv!("moo_kamera_oeffnen", mv4),
            moo_kamera_frame: decl_mv_mv!("moo_kamera_frame", mv2),
            moo_kamera_schliessen: decl_mv_mv!("moo_kamera_schliessen", mv1),
            moo_mikro_oeffnen: decl_mv_mv!("moo_mikro_oeffnen", mv3),
            moo_mikro_lesen: decl_mv_mv!("moo_mikro_lesen", mv3),
            moo_mikro_schliessen: decl_mv_mv!("moo_mikro_schliessen", mv1),
            // Webserver
            moo_web_server: decl_mv_mv!("moo_web_server", mv1),
            moo_web_accept: decl_mv_mv!("moo_web_accept", mv1),
            moo_web_respond: decl_mv_mv!("moo_web_respond", mv3),
            moo_web_json: decl_mv_mv!("moo_web_json", mv2),
            moo_web_respond_with_headers: decl_mv_mv!("moo_web_respond_with_headers", &[mv, mv, mv, mv]),
            moo_web_json_with_headers: decl_mv_mv!("moo_web_json_with_headers", &[mv, mv, mv, mv]),
            moo_web_file: decl_mv_mv!("moo_web_file", mv2),
            moo_web_template: decl_mv_mv!("moo_web_template", mv3),
        }
    }
}
