/// LLVM-Deklarationen aller C-Runtime-Funktionen.
/// Jede Funktion aus moo_runtime.h wird hier als LLVM-Funktion deklariert.

use inkwell::context::Context;
use inkwell::module::Module;
use inkwell::types::{BasicMetadataTypeEnum, BasicTypeEnum, StructType};
use inkwell::values::FunctionValue;
use inkwell::AddressSpace;

pub struct RuntimeBindings<'ctx> {
    pub moo_value_type: StructType<'ctx>,
    // Konstruktoren
    pub moo_number: FunctionValue<'ctx>,
    pub moo_string_new: FunctionValue<'ctx>,
    pub moo_bool_fn: FunctionValue<'ctx>,
    pub moo_none: FunctionValue<'ctx>,
    pub moo_list_new: FunctionValue<'ctx>,
    pub moo_dict_new: FunctionValue<'ctx>,
    pub moo_object_new: FunctionValue<'ctx>,
    // Ops
    pub moo_add: FunctionValue<'ctx>,
    pub moo_sub: FunctionValue<'ctx>,
    pub moo_mul: FunctionValue<'ctx>,
    pub moo_div: FunctionValue<'ctx>,
    pub moo_mod: FunctionValue<'ctx>,
    pub moo_pow: FunctionValue<'ctx>,
    pub moo_neg: FunctionValue<'ctx>,
    pub moo_eq: FunctionValue<'ctx>,
    pub moo_neq: FunctionValue<'ctx>,
    pub moo_lt: FunctionValue<'ctx>,
    pub moo_gt: FunctionValue<'ctx>,
    pub moo_lte: FunctionValue<'ctx>,
    pub moo_gte: FunctionValue<'ctx>,
    pub moo_and: FunctionValue<'ctx>,
    pub moo_or: FunctionValue<'ctx>,
    pub moo_not: FunctionValue<'ctx>,
    // Bitwise
    pub moo_bitand: FunctionValue<'ctx>,
    pub moo_bitor: FunctionValue<'ctx>,
    pub moo_bitxor: FunctionValue<'ctx>,
    pub moo_bitnot: FunctionValue<'ctx>,
    pub moo_lshift: FunctionValue<'ctx>,
    pub moo_rshift: FunctionValue<'ctx>,
    // Memory
    pub moo_mem_read: FunctionValue<'ctx>,
    pub moo_mem_write: FunctionValue<'ctx>,
    // String
    pub moo_string_concat: FunctionValue<'ctx>,
    // List
    pub moo_list_append: FunctionValue<'ctx>,
    pub moo_list_length: FunctionValue<'ctx>,
    pub moo_list_pop: FunctionValue<'ctx>,
    pub moo_list_sort: FunctionValue<'ctx>,
    pub moo_list_reverse: FunctionValue<'ctx>,
    pub moo_list_join: FunctionValue<'ctx>,
    pub moo_list_iter_len: FunctionValue<'ctx>,
    pub moo_list_iter_get: FunctionValue<'ctx>,
    // Dict
    pub moo_dict_get: FunctionValue<'ctx>,
    pub moo_dict_set: FunctionValue<'ctx>,
    pub moo_dict_has: FunctionValue<'ctx>,
    pub moo_dict_keys: FunctionValue<'ctx>,
    // Object
    pub moo_object_get: FunctionValue<'ctx>,
    pub moo_object_set: FunctionValue<'ctx>,
    pub moo_object_class_name: FunctionValue<'ctx>,
    pub moo_smart_close: FunctionValue<'ctx>,
    pub moo_smart_contains: FunctionValue<'ctx>,
    pub moo_socket_set_timeout: FunctionValue<'ctx>,
    pub moo_socket_read_bytes: FunctionValue<'ctx>,
    pub moo_socket_write_bytes: FunctionValue<'ctx>,
    pub moo_bytes_to_string: FunctionValue<'ctx>,
    pub moo_string_to_bytes: FunctionValue<'ctx>,
    // Events
    pub moo_event_on: FunctionValue<'ctx>,
    pub moo_event_emit: FunctionValue<'ctx>,
    // Print & convert
    pub moo_print: FunctionValue<'ctx>,
    pub moo_to_string: FunctionValue<'ctx>,
    // Error & truthiness
    pub moo_throw: FunctionValue<'ctx>,
    pub moo_try_enter: FunctionValue<'ctx>,
    pub moo_try_check: FunctionValue<'ctx>,
    pub moo_try_leave: FunctionValue<'ctx>,
    pub moo_get_error: FunctionValue<'ctx>,
    pub moo_is_truthy: FunctionValue<'ctx>,
    pub moo_is_none: FunctionValue<'ctx>,
    // Reference Counting
    pub moo_retain: FunctionValue<'ctx>,
    pub moo_release: FunctionValue<'ctx>,
    // Stdlib
    // String extras
    pub moo_string_upper: FunctionValue<'ctx>,
    pub moo_string_lower: FunctionValue<'ctx>,
    pub moo_string_trim: FunctionValue<'ctx>,
    pub moo_string_split: FunctionValue<'ctx>,
    pub moo_string_replace: FunctionValue<'ctx>,
    pub moo_string_contains: FunctionValue<'ctx>,
    pub moo_string_slice: FunctionValue<'ctx>,
    // Stdlib
    pub moo_abs: FunctionValue<'ctx>,
    pub moo_sqrt: FunctionValue<'ctx>,
    pub moo_sin: FunctionValue<'ctx>,
    pub moo_cos: FunctionValue<'ctx>,
    pub moo_tan: FunctionValue<'ctx>,
    pub moo_atan2: FunctionValue<'ctx>,
    pub moo_round: FunctionValue<'ctx>,
    pub moo_floor: FunctionValue<'ctx>,
    pub moo_ceil: FunctionValue<'ctx>,
    pub moo_min: FunctionValue<'ctx>,
    pub moo_max: FunctionValue<'ctx>,
    pub moo_random: FunctionValue<'ctx>,
    pub moo_type_of: FunctionValue<'ctx>,
    pub moo_input: FunctionValue<'ctx>,
    pub moo_length: FunctionValue<'ctx>,
    pub moo_range: FunctionValue<'ctx>,
    pub moo_time: FunctionValue<'ctx>,
    pub moo_time_ms: FunctionValue<'ctx>,
    pub moo_syscall: FunctionValue<'ctx>,
    pub moo_breakpoint: FunctionValue<'ctx>,
    pub moo_index_get: FunctionValue<'ctx>,
    pub moo_index_set: FunctionValue<'ctx>,
    // Freeze/Immutable
    pub moo_freeze: FunctionValue<'ctx>,
    pub moo_is_frozen: FunctionValue<'ctx>,
    // File I/O
    pub moo_file_read: FunctionValue<'ctx>,
    pub moo_file_write: FunctionValue<'ctx>,
    pub moo_file_read_bytes: FunctionValue<'ctx>,
    pub moo_file_write_bytes: FunctionValue<'ctx>,
    pub moo_file_append: FunctionValue<'ctx>,
    pub moo_file_lines: FunctionValue<'ctx>,
    pub moo_file_exists: FunctionValue<'ctx>,
    pub moo_file_delete: FunctionValue<'ctx>,
    pub moo_file_mtime: FunctionValue<'ctx>,
    pub moo_file_is_dir: FunctionValue<'ctx>,
    pub moo_file_mkdir: FunctionValue<'ctx>,
    pub moo_dir_list: FunctionValue<'ctx>,
    // First-Class Funktionen (MOO_FUNC-Constructors + Helpers)
    pub moo_func_new: FunctionValue<'ctx>,
    pub moo_func_with_captures: FunctionValue<'ctx>,
    pub moo_func_captured_at: FunctionValue<'ctx>,
    pub moo_func_call_0: FunctionValue<'ctx>,
    pub moo_func_call_1: FunctionValue<'ctx>,
    pub moo_func_call_2: FunctionValue<'ctx>,
    pub moo_func_call_3: FunctionValue<'ctx>,
    pub moo_func_call_4: FunctionValue<'ctx>,
    pub moo_func_call_5: FunctionValue<'ctx>,
    pub moo_func_call_6: FunctionValue<'ctx>,
    pub moo_func_call_7: FunctionValue<'ctx>,
    pub moo_func_call_8: FunctionValue<'ctx>,
    // Thread & Channel
    pub moo_thread_spawn: FunctionValue<'ctx>,
    pub moo_thread_wait: FunctionValue<'ctx>,
    pub moo_thread_done: FunctionValue<'ctx>,
    pub moo_channel_new: FunctionValue<'ctx>,
    pub moo_channel_send: FunctionValue<'ctx>,
    pub moo_channel_recv: FunctionValue<'ctx>,
    // JSON
    pub moo_json_parse: FunctionValue<'ctx>,
    pub moo_json_string: FunctionValue<'ctx>,
    // HTTP
    pub moo_http_get: FunctionValue<'ctx>,
    pub moo_http_post: FunctionValue<'ctx>,
    pub moo_http_get_with_headers: FunctionValue<'ctx>,
    pub moo_http_post_with_headers: FunctionValue<'ctx>,
    // Crypto & Security
    pub moo_sha256: FunctionValue<'ctx>,
    pub moo_sha1: FunctionValue<'ctx>,
    pub moo_sha1_bytes: FunctionValue<'ctx>,
    pub moo_secure_random: FunctionValue<'ctx>,
    pub moo_base64_encode: FunctionValue<'ctx>,
    pub moo_base64_decode: FunctionValue<'ctx>,
    pub moo_sanitize_html: FunctionValue<'ctx>,
    pub moo_sanitize_sql: FunctionValue<'ctx>,
    // Database
    pub moo_db_connect: FunctionValue<'ctx>,
    pub moo_db_execute: FunctionValue<'ctx>,
    pub moo_db_query: FunctionValue<'ctx>,
    pub moo_db_close: FunctionValue<'ctx>,
    pub moo_db_execute_with_params: FunctionValue<'ctx>,
    pub moo_db_query_with_params: FunctionValue<'ctx>,
    // Hybrid 2D+3D Pipeline (M5)
    pub moo_hybrid_create: FunctionValue<'ctx>,
    pub moo_hybrid_is_open: FunctionValue<'ctx>,
    pub moo_hybrid_clear: FunctionValue<'ctx>,
    pub moo_hybrid_update: FunctionValue<'ctx>,
    pub moo_hybrid_close: FunctionValue<'ctx>,
    pub moo_hybrid_rect_z: FunctionValue<'ctx>,
    pub moo_hybrid_line_z: FunctionValue<'ctx>,
    pub moo_hybrid_circle_z: FunctionValue<'ctx>,
    pub moo_hybrid_sprite_z: FunctionValue<'ctx>,
    pub moo_hybrid_sprite_load: FunctionValue<'ctx>,
    pub moo_db_prepare: FunctionValue<'ctx>,
    pub moo_db_stmt_bind: FunctionValue<'ctx>,
    pub moo_db_stmt_step: FunctionValue<'ctx>,
    pub moo_db_stmt_execute: FunctionValue<'ctx>,
    pub moo_db_stmt_query: FunctionValue<'ctx>,
    pub moo_db_stmt_reset: FunctionValue<'ctx>,
    // 3D Input
    pub moo_3d_key_pressed: FunctionValue<'ctx>,
    pub moo_3d_capture_mouse: FunctionValue<'ctx>,
    pub moo_3d_release_mouse: FunctionValue<'ctx>,
    pub moo_3d_mouse_dx: FunctionValue<'ctx>,
    pub moo_3d_mouse_dy: FunctionValue<'ctx>,
    pub moo_3d_mouse_x: FunctionValue<'ctx>,
    pub moo_3d_mouse_y: FunctionValue<'ctx>,
    pub moo_3d_mouse_button: FunctionValue<'ctx>,
    pub moo_3d_mouse_wheel: FunctionValue<'ctx>,
    pub moo_3d_simulate_mouse_pos: FunctionValue<'ctx>,
    pub moo_3d_simulate_mouse_button: FunctionValue<'ctx>,
    pub moo_3d_simulate_scroll: FunctionValue<'ctx>,
    pub moo_3d_screenshot_bmp: FunctionValue<'ctx>,
    // Chunk Display Lists
    pub moo_3d_chunk_create: FunctionValue<'ctx>,
    pub moo_3d_chunk_begin: FunctionValue<'ctx>,
    pub moo_3d_chunk_end: FunctionValue<'ctx>,
    pub moo_3d_chunk_draw: FunctionValue<'ctx>,
    pub moo_3d_chunk_delete: FunctionValue<'ctx>,
    // Welt (Game-Dev Runtime)
    pub moo_world_create: FunctionValue<'ctx>,
    pub moo_world_is_open: FunctionValue<'ctx>,
    pub moo_world_update: FunctionValue<'ctx>,
    pub moo_world_close: FunctionValue<'ctx>,
    pub moo_world_seed: FunctionValue<'ctx>,
    pub moo_world_biome: FunctionValue<'ctx>,
    pub moo_world_trees: FunctionValue<'ctx>,
    pub moo_world_sun: FunctionValue<'ctx>,
    pub moo_world_fog: FunctionValue<'ctx>,
    pub moo_world_sea_level: FunctionValue<'ctx>,
    pub moo_world_render_dist: FunctionValue<'ctx>,
    pub moo_world_height_at: FunctionValue<'ctx>,
    pub moo_world_time_of_day: FunctionValue<'ctx>,
    // Test-API
    pub moo_screenshot: FunctionValue<'ctx>,
    pub moo_simulate_key: FunctionValue<'ctx>,
    pub moo_simulate_mouse: FunctionValue<'ctx>,
    // Sprites (SDL2_image)
    pub moo_sprite_load: FunctionValue<'ctx>,
    pub moo_sprite_draw: FunctionValue<'ctx>,
    pub moo_sprite_draw_scaled: FunctionValue<'ctx>,
    pub moo_sprite_draw_region: FunctionValue<'ctx>,
    pub moo_sprite_width: FunctionValue<'ctx>,
    pub moo_sprite_height: FunctionValue<'ctx>,
    pub moo_sprite_free: FunctionValue<'ctx>,
    // Result-Typ
    pub moo_result_ok: FunctionValue<'ctx>,
    pub moo_result_err: FunctionValue<'ctx>,
    pub moo_result_is_ok: FunctionValue<'ctx>,
    pub moo_result_is_err: FunctionValue<'ctx>,
    pub moo_result_unwrap: FunctionValue<'ctx>,
    // Grafik (SDL2)
    pub moo_window_create: FunctionValue<'ctx>,
    pub moo_window_clear: FunctionValue<'ctx>,
    pub moo_window_update: FunctionValue<'ctx>,
    pub moo_window_is_open: FunctionValue<'ctx>,
    pub moo_window_close: FunctionValue<'ctx>,
    pub moo_draw_rect: FunctionValue<'ctx>,
    pub moo_draw_circle: FunctionValue<'ctx>,
    pub moo_draw_line: FunctionValue<'ctx>,
    pub moo_draw_pixel: FunctionValue<'ctx>,
    // Grafik Input (SDL2)
    pub moo_key_pressed: FunctionValue<'ctx>,
    pub moo_mouse_x: FunctionValue<'ctx>,
    pub moo_mouse_y: FunctionValue<'ctx>,
    pub moo_mouse_pressed: FunctionValue<'ctx>,
    pub moo_delay: FunctionValue<'ctx>,
    // 3D Grafik (OpenGL/Software)
    pub moo_3d_create: FunctionValue<'ctx>,
    pub moo_3d_is_open: FunctionValue<'ctx>,
    pub moo_3d_clear: FunctionValue<'ctx>,
    pub moo_3d_update: FunctionValue<'ctx>,
    pub moo_3d_close: FunctionValue<'ctx>,
    pub moo_3d_perspective: FunctionValue<'ctx>,
    pub moo_3d_camera: FunctionValue<'ctx>,
    pub moo_3d_rotate: FunctionValue<'ctx>,
    pub moo_3d_translate: FunctionValue<'ctx>,
    pub moo_3d_push: FunctionValue<'ctx>,
    pub moo_3d_pop: FunctionValue<'ctx>,
    pub moo_3d_triangle: FunctionValue<'ctx>,
    pub moo_3d_cube: FunctionValue<'ctx>,
    pub moo_3d_sphere: FunctionValue<'ctx>,
    // Regex (POSIX)
    pub moo_regex_new: FunctionValue<'ctx>,
    pub moo_regex_match: FunctionValue<'ctx>,
    pub moo_regex_find: FunctionValue<'ctx>,
    pub moo_regex_find_all: FunctionValue<'ctx>,
    pub moo_regex_replace: FunctionValue<'ctx>,
    // Kern-Builtins
    pub moo_sleep: FunctionValue<'ctx>,
    pub moo_env: FunctionValue<'ctx>,
    pub moo_exit: FunctionValue<'ctx>,
    pub moo_to_number: FunctionValue<'ctx>,
    pub moo_args: FunctionValue<'ctx>,
    pub moo_pid: FunctionValue<'ctx>,
    // Tray (System-Tray) — erweitert (moo_tray.h)
    pub moo_tray_create: FunctionValue<'ctx>,
    pub moo_tray_titel_setze: FunctionValue<'ctx>,
    pub moo_tray_icon_setze: FunctionValue<'ctx>,
    pub moo_tray_aktiv: FunctionValue<'ctx>,
    pub moo_tray_menu_add: FunctionValue<'ctx>,
    pub moo_tray_separator_add: FunctionValue<'ctx>,
    pub moo_tray_menu_clear: FunctionValue<'ctx>,
    pub moo_tray_submenu_add: FunctionValue<'ctx>,
    pub moo_tray_menu_add_to: FunctionValue<'ctx>,
    pub moo_tray_separator_add_to: FunctionValue<'ctx>,
    pub moo_tray_check_add: FunctionValue<'ctx>,
    pub moo_tray_check_add_to: FunctionValue<'ctx>,
    pub moo_tray_check_wert: FunctionValue<'ctx>,
    pub moo_tray_check_set: FunctionValue<'ctx>,
    pub moo_tray_item_aktiv: FunctionValue<'ctx>,
    pub moo_tray_item_label_setze: FunctionValue<'ctx>,
    pub moo_tray_timer_add: FunctionValue<'ctx>,
    pub moo_tray_timer_remove: FunctionValue<'ctx>,
    pub moo_tray_run: FunctionValue<'ctx>,
    // UI (Cross-Platform Widgets — moo_ui.h)
    pub moo_ui_init: FunctionValue<'ctx>,
    pub moo_ui_laufen: FunctionValue<'ctx>,
    pub moo_ui_beenden: FunctionValue<'ctx>,
    pub moo_ui_pump: FunctionValue<'ctx>,
    pub moo_ui_debug: FunctionValue<'ctx>,
    pub moo_ui_fenster: FunctionValue<'ctx>,
    pub moo_ui_fenster_titel_setze: FunctionValue<'ctx>,
    pub moo_ui_fenster_icon_setze: FunctionValue<'ctx>,
    pub moo_ui_fenster_groesse_setze: FunctionValue<'ctx>,
    pub moo_ui_fenster_position_setze: FunctionValue<'ctx>,
    pub moo_ui_fenster_schliessen: FunctionValue<'ctx>,
    pub moo_ui_zeige: FunctionValue<'ctx>,
    pub moo_ui_zeige_nebenbei: FunctionValue<'ctx>,
    pub moo_ui_fenster_on_close: FunctionValue<'ctx>,
    pub moo_ui_fenster_on_resize: FunctionValue<'ctx>,
    pub moo_ui_label: FunctionValue<'ctx>,
    pub moo_ui_label_setze: FunctionValue<'ctx>,
    pub moo_ui_label_text: FunctionValue<'ctx>,
    pub moo_ui_knopf: FunctionValue<'ctx>,
    pub moo_ui_checkbox: FunctionValue<'ctx>,
    pub moo_ui_checkbox_wert: FunctionValue<'ctx>,
    pub moo_ui_checkbox_setze: FunctionValue<'ctx>,
    pub moo_ui_radio: FunctionValue<'ctx>,
    pub moo_ui_radio_wert: FunctionValue<'ctx>,
    pub moo_ui_eingabe: FunctionValue<'ctx>,
    pub moo_ui_eingabe_text: FunctionValue<'ctx>,
    pub moo_ui_eingabe_setze: FunctionValue<'ctx>,
    pub moo_ui_eingabe_on_change: FunctionValue<'ctx>,
    pub moo_ui_eingabe_on_enter: FunctionValue<'ctx>,
    pub moo_ui_textbereich: FunctionValue<'ctx>,
    pub moo_ui_textbereich_text: FunctionValue<'ctx>,
    pub moo_ui_textbereich_setze: FunctionValue<'ctx>,
    pub moo_ui_textbereich_anhaengen: FunctionValue<'ctx>,
    pub moo_ui_textbereich_on_key: FunctionValue<'ctx>,
    pub moo_ui_textbereich_zeile_anzahl: FunctionValue<'ctx>,
    pub moo_ui_dropdown: FunctionValue<'ctx>,
    pub moo_ui_dropdown_auswahl: FunctionValue<'ctx>,
    pub moo_ui_dropdown_auswahl_setze: FunctionValue<'ctx>,
    pub moo_ui_dropdown_text: FunctionValue<'ctx>,
    pub moo_ui_liste: FunctionValue<'ctx>,
    pub moo_ui_liste_zeile_hinzu: FunctionValue<'ctx>,
    pub moo_ui_liste_auswahl: FunctionValue<'ctx>,
    pub moo_ui_liste_zeile: FunctionValue<'ctx>,
    pub moo_ui_liste_leeren: FunctionValue<'ctx>,
    pub moo_ui_liste_on_auswahl: FunctionValue<'ctx>,
    pub moo_ui_liste_on_scroll: FunctionValue<'ctx>,
    pub moo_ui_liste_scroll_zu: FunctionValue<'ctx>,
    pub moo_ui_liste_scroll_unten: FunctionValue<'ctx>,
    pub moo_ui_liste_spalte_breite: FunctionValue<'ctx>,
    pub moo_ui_liste_sortierbar: FunctionValue<'ctx>,
    pub moo_ui_liste_sortiere: FunctionValue<'ctx>,
    pub moo_ui_liste_zeile_setze: FunctionValue<'ctx>,
    pub moo_ui_liste_zelle_setze: FunctionValue<'ctx>,
    pub moo_ui_liste_entferne: FunctionValue<'ctx>,
    pub moo_ui_slider: FunctionValue<'ctx>,
    pub moo_ui_slider_wert: FunctionValue<'ctx>,
    pub moo_ui_slider_setze: FunctionValue<'ctx>,
    pub moo_ui_fortschritt: FunctionValue<'ctx>,
    pub moo_ui_fortschritt_setze: FunctionValue<'ctx>,
    pub moo_ui_bild: FunctionValue<'ctx>,
    pub moo_ui_bild_setze: FunctionValue<'ctx>,
    pub moo_ui_leinwand: FunctionValue<'ctx>,
    pub moo_ui_leinwand_anfordern: FunctionValue<'ctx>,
    pub moo_ui_leinwand_on_maus: FunctionValue<'ctx>,
    pub moo_ui_leinwand_on_bewegung: FunctionValue<'ctx>,
    pub moo_ui_zeichne_farbe: FunctionValue<'ctx>,
    pub moo_ui_zeichne_linie: FunctionValue<'ctx>,
    pub moo_ui_zeichne_rechteck: FunctionValue<'ctx>,
    pub moo_ui_zeichne_kreis: FunctionValue<'ctx>,
    pub moo_ui_zeichne_text: FunctionValue<'ctx>,
    pub moo_ui_zeichne_text_breite: FunctionValue<'ctx>,
    pub moo_ui_zeichne_bild: FunctionValue<'ctx>,
    pub moo_ui_rahmen: FunctionValue<'ctx>,
    pub moo_ui_trenner: FunctionValue<'ctx>,
    pub moo_ui_tabs: FunctionValue<'ctx>,
    pub moo_ui_tab_hinzu: FunctionValue<'ctx>,
    pub moo_ui_tabs_auswahl: FunctionValue<'ctx>,
    pub moo_ui_tabs_auswahl_setze: FunctionValue<'ctx>,
    pub moo_ui_scroll: FunctionValue<'ctx>,
    pub moo_ui_sichtbar: FunctionValue<'ctx>,
    pub moo_ui_aktiv: FunctionValue<'ctx>,
    pub moo_ui_position_setze: FunctionValue<'ctx>,
    pub moo_ui_groesse_setze: FunctionValue<'ctx>,
    pub moo_ui_farbe_setze: FunctionValue<'ctx>,
    pub moo_ui_schrift_setze: FunctionValue<'ctx>,
    pub moo_ui_tooltip_setze: FunctionValue<'ctx>,
    pub moo_ui_zerstoere: FunctionValue<'ctx>,
    pub moo_ui_widget_id_setze: FunctionValue<'ctx>,
    pub moo_ui_widget_id_hole: FunctionValue<'ctx>,
    pub moo_ui_widget_info: FunctionValue<'ctx>,
    pub moo_ui_widget_baum: FunctionValue<'ctx>,
    pub moo_ui_widget_suche: FunctionValue<'ctx>,
    pub moo_ui_test_snapshot: FunctionValue<'ctx>,
    pub moo_ui_test_snapshot_widget: FunctionValue<'ctx>,
    pub moo_ui_test_klick: FunctionValue<'ctx>,
    pub moo_ui_test_klick_xy: FunctionValue<'ctx>,
    pub moo_ui_test_text_setze: FunctionValue<'ctx>,
    pub moo_ui_test_shortcut: FunctionValue<'ctx>,
    pub moo_ui_test_warte: FunctionValue<'ctx>,
    pub moo_ui_test_pump: FunctionValue<'ctx>,
    pub moo_ui_timer_hinzu: FunctionValue<'ctx>,
    pub moo_ui_timer_entfernen: FunctionValue<'ctx>,
    pub moo_ui_info: FunctionValue<'ctx>,
    pub moo_ui_warnung: FunctionValue<'ctx>,
    pub moo_ui_fehler: FunctionValue<'ctx>,
    pub moo_ui_frage: FunctionValue<'ctx>,
    pub moo_ui_eingabe_dialog: FunctionValue<'ctx>,
    pub moo_ui_datei_oeffnen: FunctionValue<'ctx>,
    pub moo_ui_datei_speichern: FunctionValue<'ctx>,
    pub moo_ui_ordner_waehlen: FunctionValue<'ctx>,
    pub moo_ui_menueleiste: FunctionValue<'ctx>,
    pub moo_ui_menue: FunctionValue<'ctx>,
    pub moo_ui_menue_eintrag: FunctionValue<'ctx>,
    pub moo_ui_menue_trenner: FunctionValue<'ctx>,
    pub moo_ui_menue_untermenue: FunctionValue<'ctx>,
    pub moo_ui_shortcut_bind: FunctionValue<'ctx>,
    pub moo_ui_shortcut_loese: FunctionValue<'ctx>,
    // Netzwerk (TCP/UDP)
    pub moo_tcp_server: FunctionValue<'ctx>,
    pub moo_tcp_connect: FunctionValue<'ctx>,
    pub moo_udp_socket: FunctionValue<'ctx>,
    pub moo_udp_connect: FunctionValue<'ctx>,
    pub moo_socket_accept: FunctionValue<'ctx>,
    pub moo_socket_read: FunctionValue<'ctx>,
    pub moo_socket_write: FunctionValue<'ctx>,
    // Profiler
    pub moo_profile_enter: FunctionValue<'ctx>,
    pub moo_profile_exit: FunctionValue<'ctx>,
    pub moo_profile_report: FunctionValue<'ctx>,
    // Eval
    pub moo_eval: FunctionValue<'ctx>,
    // Webserver
    pub moo_web_server: FunctionValue<'ctx>,
    pub moo_web_accept: FunctionValue<'ctx>,
    pub moo_web_respond: FunctionValue<'ctx>,
    pub moo_web_json: FunctionValue<'ctx>,
    pub moo_web_respond_with_headers: FunctionValue<'ctx>,
    pub moo_web_json_with_headers: FunctionValue<'ctx>,
    pub moo_web_file: FunctionValue<'ctx>,
    pub moo_web_template: FunctionValue<'ctx>,
}

impl<'ctx> RuntimeBindings<'ctx> {
    pub fn declare(context: &'ctx Context, module: &Module<'ctx>) -> Self {
        let ptr_type = context.ptr_type(AddressSpace::default());
        let i32_type = context.i32_type();
        let i8_type = context.i8_type();
        let f64_type = context.f64_type();
        let void_type = context.void_type();
        let bool_type = context.bool_type();

        // MooValue = { uint8_t tag, [7 padding], union { double, ptr } data }
        // C-ABI: sizeof = 16, tag at offset 0, data at offset 8
        // LLVM: { i64, double } passt exakt (8 + 8 = 16 Bytes, korrektes Alignment)
        let i64_type = context.i64_type();
        // MooValue = { uint64_t tag, uint64_t data } — exakt 16 Bytes
        let moo_value_type = context.struct_type(
            &[i64_type.into(), i64_type.into()],
            false,
        );

        let mv: BasicMetadataTypeEnum = moo_value_type.into();
        let mv1 = &[mv];
        let mv2 = &[mv, mv];
        let mv3 = &[mv, mv, mv];

        // Makro fuer Deklaration
        macro_rules! decl {
            ($name:expr, ret $ret:expr, $($params:expr),*) => {
                module.add_function($name, $ret.fn_type(&[$($params.into()),*], false), None)
            };
        }

        // MooValue-returning, N MooValue params
        macro_rules! decl_mv_mv {
            ($name:expr, $params:expr) => {
                module.add_function($name, moo_value_type.fn_type($params, false), None)
            };
        }

        Self {
            moo_value_type,

            // Konstruktoren
            moo_number: decl_mv_mv!("moo_number", &[f64_type.into()]),
            moo_string_new: decl_mv_mv!("moo_string_new", &[ptr_type.into()]),
            moo_bool_fn: decl_mv_mv!("moo_bool", &[bool_type.into()]),
            moo_none: decl_mv_mv!("moo_none", &[]),
            moo_list_new: decl_mv_mv!("moo_list_new", &[i32_type.into()]),
            moo_dict_new: decl_mv_mv!("moo_dict_new", &[]),
            moo_object_new: decl_mv_mv!("moo_object_new", &[ptr_type.into()]),

            // Ops (MooValue, MooValue) -> MooValue
            moo_add: decl_mv_mv!("moo_add", mv2),
            moo_sub: decl_mv_mv!("moo_sub", mv2),
            moo_mul: decl_mv_mv!("moo_mul", mv2),
            moo_div: decl_mv_mv!("moo_div", mv2),
            moo_mod: decl_mv_mv!("moo_mod", mv2),
            moo_pow: decl_mv_mv!("moo_pow", mv2),
            moo_neg: decl_mv_mv!("moo_neg", mv1),
            moo_eq: decl_mv_mv!("moo_eq", mv2),
            moo_neq: decl_mv_mv!("moo_neq", mv2),
            moo_lt: decl_mv_mv!("moo_lt", mv2),
            moo_gt: decl_mv_mv!("moo_gt", mv2),
            moo_lte: decl_mv_mv!("moo_lte", mv2),
            moo_gte: decl_mv_mv!("moo_gte", mv2),
            moo_and: decl_mv_mv!("moo_and", mv2),
            moo_or: decl_mv_mv!("moo_or", mv2),
            moo_not: decl_mv_mv!("moo_not", mv1),

            // Bitwise
            moo_bitand: decl_mv_mv!("moo_bitand", mv2),
            moo_bitor: decl_mv_mv!("moo_bitor", mv2),
            moo_bitxor: decl_mv_mv!("moo_bitxor", mv2),
            moo_bitnot: decl_mv_mv!("moo_bitnot", mv1),
            moo_lshift: decl_mv_mv!("moo_lshift", mv2),
            moo_rshift: decl_mv_mv!("moo_rshift", mv2),
            // Memory
            moo_mem_read: decl_mv_mv!("moo_mem_read", mv2),
            moo_mem_write: module.add_function("moo_mem_write", void_type.fn_type(mv3, false), None),

            // String
            moo_string_concat: decl_mv_mv!("moo_string_concat", mv2),
            // List
            moo_list_append: module.add_function("moo_list_append", void_type.fn_type(mv2, false), None),
            moo_list_length: decl_mv_mv!("moo_list_length", mv1),
            moo_list_pop: decl_mv_mv!("moo_list_pop", mv1),
            moo_list_sort: decl_mv_mv!("moo_list_sort", mv1),
            moo_list_reverse: decl_mv_mv!("moo_list_reverse", mv1),
            moo_list_join: decl_mv_mv!("moo_list_join", mv2),
            moo_list_iter_len: module.add_function("moo_list_iter_len", i32_type.fn_type(mv1, false), None),
            moo_list_iter_get: decl_mv_mv!("moo_list_iter_get", &[mv, i32_type.into()]),

            // Dict
            moo_dict_get: decl_mv_mv!("moo_dict_get", mv2),
            moo_dict_set: module.add_function("moo_dict_set", void_type.fn_type(mv3, false), None),
            moo_dict_has: decl_mv_mv!("moo_dict_has", mv2),
            moo_dict_keys: decl_mv_mv!("moo_dict_keys", mv1),

            // Object
            moo_object_get: decl_mv_mv!("moo_object_get", &[mv, ptr_type.into()]),
            moo_object_set: module.add_function("moo_object_set", void_type.fn_type(&[mv, ptr_type.into(), mv], false), None),
            moo_object_class_name: module.add_function("moo_object_class_name", ptr_type.fn_type(mv1, false), None),
            moo_smart_close: module.add_function("moo_smart_close", void_type.fn_type(mv1, false), None),
            moo_smart_contains: decl_mv_mv!("moo_smart_contains", mv2),
            moo_socket_set_timeout: module.add_function("moo_socket_set_timeout", void_type.fn_type(mv2, false), None),
            moo_socket_read_bytes: decl_mv_mv!("moo_socket_read_bytes", mv2),
            moo_socket_write_bytes: module.add_function("moo_socket_write_bytes", void_type.fn_type(mv2, false), None),
            moo_bytes_to_string: decl_mv_mv!("moo_bytes_to_string", mv1),
            moo_string_to_bytes: decl_mv_mv!("moo_string_to_bytes", mv1),
            // Events
            moo_event_on: module.add_function("moo_event_on", void_type.fn_type(mv3, false), None),
            moo_event_emit: module.add_function("moo_event_emit", void_type.fn_type(mv2, false), None),

            // Print & convert
            moo_print: module.add_function("moo_print", void_type.fn_type(mv1, false), None),
            moo_to_string: decl_mv_mv!("moo_to_string", mv1),

            // Error & truthiness
            moo_throw: module.add_function("moo_throw", void_type.fn_type(mv1, false), None),
            moo_try_enter: module.add_function("moo_try_enter", void_type.fn_type(&[], false), None),
            moo_try_check: module.add_function("moo_try_check", i32_type.fn_type(&[], false), None),
            moo_try_leave: module.add_function("moo_try_leave", void_type.fn_type(&[], false), None),
            moo_get_error: decl_mv_mv!("moo_get_error", &[]),
            moo_is_truthy: module.add_function("moo_is_truthy", bool_type.fn_type(mv1, false), None),
            moo_is_none: module.add_function("moo_is_none", bool_type.fn_type(mv1, false), None),
            // Reference Counting
            moo_retain: module.add_function("moo_retain", void_type.fn_type(mv1, false), None),
            moo_release: module.add_function("moo_release", void_type.fn_type(mv1, false), None),

            // String extras
            moo_string_upper: decl_mv_mv!("moo_string_upper", mv1),
            moo_string_lower: decl_mv_mv!("moo_string_lower", mv1),
            moo_string_trim: decl_mv_mv!("moo_string_trim", mv1),
            moo_string_split: decl_mv_mv!("moo_string_split", mv2),
            moo_string_replace: decl_mv_mv!("moo_string_replace", &[mv, mv, mv]),
            moo_string_contains: decl_mv_mv!("moo_string_contains", mv2),
            moo_string_slice: decl_mv_mv!("moo_string_slice", mv3),
            // Stdlib
            moo_abs: decl_mv_mv!("moo_abs", mv1),
            moo_sqrt: decl_mv_mv!("moo_sqrt", mv1),
            moo_sin: decl_mv_mv!("moo_sin", mv1),
            moo_cos: decl_mv_mv!("moo_cos", mv1),
            moo_tan: decl_mv_mv!("moo_tan", mv1),
            moo_atan2: decl_mv_mv!("moo_atan2", mv2),
            moo_round: decl_mv_mv!("moo_round", mv1),
            moo_floor: decl_mv_mv!("moo_floor", mv1),
            moo_ceil: decl_mv_mv!("moo_ceil", mv1),
            moo_min: decl_mv_mv!("moo_min", mv2),
            moo_max: decl_mv_mv!("moo_max", mv2),
            moo_random: decl_mv_mv!("moo_random", &[]),
            moo_type_of: decl_mv_mv!("moo_type_of", mv1),
            moo_input: decl_mv_mv!("moo_input", mv1),
            moo_length: decl_mv_mv!("moo_length", mv1),
            moo_range: decl_mv_mv!("moo_range", mv2),
            moo_time: decl_mv_mv!("moo_time", &[]),
            moo_time_ms: decl_mv_mv!("moo_time_ms", &[]),
            moo_syscall: decl_mv_mv!("moo_syscall", &[mv, mv, mv, mv]),
            moo_breakpoint: module.add_function("moo_breakpoint", void_type.fn_type(mv1, false), None),
            moo_index_get: decl_mv_mv!("moo_index_get", mv2),
            moo_index_set: module.add_function("moo_index_set", void_type.fn_type(mv3, false), None),
            // Freeze/Immutable
            moo_freeze: decl_mv_mv!("moo_freeze", mv1),
            moo_is_frozen: decl_mv_mv!("moo_is_frozen", mv1),
            // File I/O
            moo_file_read: decl_mv_mv!("moo_file_read", mv1),
            moo_file_write: decl_mv_mv!("moo_file_write", mv2),
            moo_file_read_bytes: decl_mv_mv!("moo_file_read_bytes", mv1),
            moo_file_write_bytes: decl_mv_mv!("moo_file_write_bytes", mv2),
            moo_file_append: decl_mv_mv!("moo_file_append", mv2),
            moo_file_lines: decl_mv_mv!("moo_file_lines", mv1),
            moo_file_exists: decl_mv_mv!("moo_file_exists", mv1),
            moo_file_delete: decl_mv_mv!("moo_file_delete", mv1),
            moo_file_mtime: decl_mv_mv!("moo_file_mtime", mv1),
            moo_file_is_dir: decl_mv_mv!("moo_file_is_dir", mv1),
            moo_file_mkdir: decl_mv_mv!("moo_file_mkdir", mv1),
            moo_dir_list: decl_mv_mv!("moo_dir_list", mv1),
            // First-Class Funktionen
            // moo_func_new(void* fn_ptr, int32 arity, const char* name) -> MooValue
            moo_func_new: module.add_function("moo_func_new",
                moo_value_type.fn_type(&[ptr_type.into(), i32_type.into(), ptr_type.into()], false),
                None),
            // moo_func_with_captures(void* tramp, int32 arity, const char* name,
            //                        MooValue* caps, int32 n) -> MooValue
            moo_func_with_captures: module.add_function("moo_func_with_captures",
                moo_value_type.fn_type(&[
                    ptr_type.into(), i32_type.into(), ptr_type.into(),
                    ptr_type.into(), i32_type.into(),
                ], false),
                None),
            // moo_func_captured_at(MooFunc* fn, int32 i) -> MooValue
            moo_func_captured_at: module.add_function("moo_func_captured_at",
                moo_value_type.fn_type(&[ptr_type.into(), i32_type.into()], false),
                None),
            moo_func_call_0: decl_mv_mv!("moo_func_call_0", mv1),
            moo_func_call_1: decl_mv_mv!("moo_func_call_1", mv2),
            moo_func_call_2: decl_mv_mv!("moo_func_call_2", mv3),
            moo_func_call_3: decl_mv_mv!("moo_func_call_3", &[mv, mv, mv, mv]),
            moo_func_call_4: decl_mv_mv!("moo_func_call_4", &[mv, mv, mv, mv, mv]),
            moo_func_call_5: decl_mv_mv!("moo_func_call_5", &[mv, mv, mv, mv, mv, mv]),
            moo_func_call_6: decl_mv_mv!("moo_func_call_6", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_func_call_7: decl_mv_mv!("moo_func_call_7", &[mv, mv, mv, mv, mv, mv, mv, mv]),
            moo_func_call_8: decl_mv_mv!("moo_func_call_8", &[mv, mv, mv, mv, mv, mv, mv, mv, mv]),
            // Thread & Channel
            moo_thread_spawn: decl_mv_mv!("moo_thread_spawn", mv2),
            moo_thread_wait: decl_mv_mv!("moo_thread_wait", mv1),
            moo_thread_done: decl_mv_mv!("moo_thread_done", mv1),
            moo_channel_new: decl_mv_mv!("moo_channel_new", mv1),
            moo_channel_send: module.add_function("moo_channel_send", void_type.fn_type(mv2, false), None),
            moo_channel_recv: decl_mv_mv!("moo_channel_recv", mv1),
            // JSON
            moo_json_parse: decl_mv_mv!("moo_json_parse", mv1),
            moo_json_string: decl_mv_mv!("moo_json_string", mv1),
            // HTTP
            moo_http_get: decl_mv_mv!("moo_http_get", mv1),
            moo_http_post: decl_mv_mv!("moo_http_post", mv2),
            moo_http_get_with_headers: decl_mv_mv!("moo_http_get_with_headers", mv2),
            moo_http_post_with_headers: decl_mv_mv!("moo_http_post_with_headers", mv3),
            // Crypto & Security
            moo_sha256: decl_mv_mv!("moo_sha256", mv1),
            moo_sha1: decl_mv_mv!("moo_sha1", mv1),
            moo_sha1_bytes: decl_mv_mv!("moo_sha1_bytes", mv1),
            moo_secure_random: decl_mv_mv!("moo_secure_random", mv1),
            moo_base64_encode: decl_mv_mv!("moo_base64_encode", mv1),
            moo_base64_decode: decl_mv_mv!("moo_base64_decode", mv1),
            moo_sanitize_html: decl_mv_mv!("moo_sanitize_html", mv1),
            moo_sanitize_sql: decl_mv_mv!("moo_sanitize_sql", mv1),
            // Database
            moo_db_connect: decl_mv_mv!("moo_db_connect", mv1),
            moo_db_execute: decl_mv_mv!("moo_db_execute", mv2),
            moo_db_query: decl_mv_mv!("moo_db_query", mv2),
            moo_db_close: module.add_function("moo_db_close", void_type.fn_type(mv1, false), None),
            moo_db_execute_with_params: decl_mv_mv!("moo_db_execute_with_params", mv3),
            moo_db_query_with_params: decl_mv_mv!("moo_db_query_with_params", mv3),
            // Hybrid 2D+3D (M5)
            moo_hybrid_create: decl_mv_mv!("moo_hybrid_create", mv3),
            moo_hybrid_is_open: decl_mv_mv!("moo_hybrid_is_open", mv1),
            moo_hybrid_clear: module.add_function("moo_hybrid_clear", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_hybrid_update: module.add_function("moo_hybrid_update", void_type.fn_type(mv1, false), None),
            moo_hybrid_close: module.add_function("moo_hybrid_close", void_type.fn_type(mv1, false), None),
            moo_hybrid_rect_z: module.add_function("moo_hybrid_rect_z", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_hybrid_line_z: module.add_function("moo_hybrid_line_z", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_hybrid_circle_z: module.add_function("moo_hybrid_circle_z", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_hybrid_sprite_z: module.add_function("moo_hybrid_sprite_z", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_hybrid_sprite_load: decl_mv_mv!("moo_hybrid_sprite_load", mv2),
            moo_db_prepare: decl_mv_mv!("moo_db_prepare", mv2),
            moo_db_stmt_bind: decl_mv_mv!("moo_db_stmt_bind", mv3),
            moo_db_stmt_step: decl_mv_mv!("moo_db_stmt_step", mv1),
            moo_db_stmt_execute: decl_mv_mv!("moo_db_stmt_execute", mv1),
            moo_db_stmt_query: decl_mv_mv!("moo_db_stmt_query", mv1),
            moo_db_stmt_reset: decl_mv_mv!("moo_db_stmt_reset", mv1),
            // Result-Typ
            moo_3d_key_pressed: decl_mv_mv!("moo_3d_key_pressed", mv2),
            moo_3d_capture_mouse: module.add_function("moo_3d_capture_mouse", void_type.fn_type(mv1, false), None),
            moo_3d_release_mouse: module.add_function("moo_3d_release_mouse", void_type.fn_type(mv1, false), None),
            moo_3d_mouse_dx: decl_mv_mv!("moo_3d_mouse_dx", mv1),
            moo_3d_mouse_dy: decl_mv_mv!("moo_3d_mouse_dy", mv1),
            moo_3d_mouse_x: decl_mv_mv!("moo_3d_mouse_x", mv1),
            moo_3d_mouse_y: decl_mv_mv!("moo_3d_mouse_y", mv1),
            moo_3d_mouse_button: decl_mv_mv!("moo_3d_mouse_button", mv2),
            moo_3d_mouse_wheel: decl_mv_mv!("moo_3d_mouse_wheel", mv1),
            moo_3d_simulate_mouse_pos: module.add_function("moo_3d_simulate_mouse_pos", void_type.fn_type(mv3, false), None),
            moo_3d_simulate_mouse_button: module.add_function("moo_3d_simulate_mouse_button", void_type.fn_type(mv3, false), None),
            moo_3d_simulate_scroll: module.add_function("moo_3d_simulate_scroll", void_type.fn_type(mv2, false), None),
            moo_3d_screenshot_bmp: decl_mv_mv!("moo_3d_screenshot_bmp", mv2),
            // Chunk Display Lists
            moo_3d_chunk_create: decl_mv_mv!("moo_3d_chunk_create", &[]),
            moo_3d_chunk_begin: module.add_function("moo_3d_chunk_begin", void_type.fn_type(mv1, false), None),
            moo_3d_chunk_end: module.add_function("moo_3d_chunk_end", void_type.fn_type(&[], false), None),
            moo_3d_chunk_draw: module.add_function("moo_3d_chunk_draw", void_type.fn_type(mv1, false), None),
            moo_3d_chunk_delete: module.add_function("moo_3d_chunk_delete", void_type.fn_type(mv1, false), None),
            // Welt (Game-Dev Runtime)
            moo_world_create: decl_mv_mv!("moo_world_create", mv3),
            moo_world_is_open: decl_mv_mv!("moo_world_is_open", mv1),
            moo_world_update: module.add_function("moo_world_update", void_type.fn_type(mv1, false), None),
            moo_world_close: module.add_function("moo_world_close", void_type.fn_type(mv1, false), None),
            moo_world_seed: module.add_function("moo_world_seed", void_type.fn_type(mv2, false), None),
            moo_world_biome: module.add_function("moo_world_biome", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_world_trees: module.add_function("moo_world_trees", void_type.fn_type(mv3, false), None),
            moo_world_sun: module.add_function("moo_world_sun", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_world_fog: module.add_function("moo_world_fog", void_type.fn_type(mv2, false), None),
            moo_world_sea_level: module.add_function("moo_world_sea_level", void_type.fn_type(mv2, false), None),
            moo_world_render_dist: module.add_function("moo_world_render_dist", void_type.fn_type(mv2, false), None),
            moo_world_height_at: decl_mv_mv!("moo_world_height_at", mv3),
            moo_world_time_of_day: module.add_function("moo_world_time_of_day", void_type.fn_type(mv2, false), None),
            // Test-API
            moo_screenshot: decl_mv_mv!("moo_screenshot", mv2),
            moo_simulate_key: module.add_function("moo_simulate_key", void_type.fn_type(mv2, false), None),
            moo_simulate_mouse: module.add_function("moo_simulate_mouse", void_type.fn_type(mv3, false), None),
            // Sprites
            moo_sprite_load: decl_mv_mv!("moo_sprite_load", mv2),
            moo_sprite_draw: module.add_function("moo_sprite_draw", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_sprite_draw_scaled: module.add_function("moo_sprite_draw_scaled", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_sprite_draw_region: module.add_function("moo_sprite_draw_region", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_sprite_width: decl_mv_mv!("moo_sprite_width", mv1),
            moo_sprite_height: decl_mv_mv!("moo_sprite_height", mv1),
            moo_sprite_free: module.add_function("moo_sprite_free", void_type.fn_type(mv1, false), None),
            moo_result_ok: decl_mv_mv!("moo_result_ok", mv1),
            moo_result_err: decl_mv_mv!("moo_result_err", mv1),
            moo_result_is_ok: decl_mv_mv!("moo_result_is_ok", mv1),
            moo_result_is_err: decl_mv_mv!("moo_result_is_err", mv1),
            moo_result_unwrap: decl_mv_mv!("moo_result_unwrap", mv1),
            // Grafik (SDL2)
            moo_window_create: decl_mv_mv!("moo_window_create", mv3),
            moo_window_clear: module.add_function("moo_window_clear", void_type.fn_type(mv2, false), None),
            moo_window_update: module.add_function("moo_window_update", void_type.fn_type(mv1, false), None),
            moo_window_is_open: decl_mv_mv!("moo_window_is_open", mv1),
            moo_window_close: module.add_function("moo_window_close", void_type.fn_type(mv1, false), None),
            moo_draw_rect: module.add_function("moo_draw_rect", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_draw_circle: module.add_function("moo_draw_circle", void_type.fn_type(&[mv, mv, mv, mv, mv], false), None),
            moo_draw_line: module.add_function("moo_draw_line", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_draw_pixel: module.add_function("moo_draw_pixel", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            // Grafik Input (SDL2)
            moo_key_pressed: decl_mv_mv!("moo_key_pressed", mv1),
            moo_mouse_x: decl_mv_mv!("moo_mouse_x", mv1),
            moo_mouse_y: decl_mv_mv!("moo_mouse_y", mv1),
            moo_mouse_pressed: decl_mv_mv!("moo_mouse_pressed", mv1),
            moo_delay: module.add_function("moo_delay", void_type.fn_type(mv1, false), None),
            // 3D Grafik
            moo_3d_create: decl_mv_mv!("moo_3d_create", mv3),
            moo_3d_is_open: decl_mv_mv!("moo_3d_is_open", mv1),
            moo_3d_clear: module.add_function("moo_3d_clear", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_3d_update: module.add_function("moo_3d_update", void_type.fn_type(mv1, false), None),
            moo_3d_close: module.add_function("moo_3d_close", void_type.fn_type(mv1, false), None),
            moo_3d_perspective: module.add_function("moo_3d_perspective", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_3d_camera: module.add_function("moo_3d_camera", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_3d_rotate: module.add_function("moo_3d_rotate", void_type.fn_type(&[mv, mv, mv, mv, mv], false), None),
            moo_3d_translate: module.add_function("moo_3d_translate", void_type.fn_type(&[mv, mv, mv, mv], false), None),
            moo_3d_push: module.add_function("moo_3d_push", void_type.fn_type(mv1, false), None),
            moo_3d_pop: module.add_function("moo_3d_pop", void_type.fn_type(mv1, false), None),
            moo_3d_triangle: module.add_function("moo_3d_triangle", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv, mv, mv, mv, mv], false), None),
            moo_3d_cube: module.add_function("moo_3d_cube", void_type.fn_type(&[mv, mv, mv, mv, mv, mv], false), None),
            moo_3d_sphere: module.add_function("moo_3d_sphere", void_type.fn_type(&[mv, mv, mv, mv, mv, mv, mv], false), None),
            // Regex
            moo_regex_new: decl_mv_mv!("moo_regex_new", mv1),
            moo_regex_match: decl_mv_mv!("moo_regex_match", mv2),
            moo_regex_find: decl_mv_mv!("moo_regex_find", mv2),
            moo_regex_find_all: decl_mv_mv!("moo_regex_find_all", mv2),
            moo_regex_replace: decl_mv_mv!("moo_regex_replace", mv3),
            // Kern-Builtins
            moo_sleep: module.add_function("moo_sleep", void_type.fn_type(mv1, false), None),
            moo_env: decl_mv_mv!("moo_env", mv1),
            moo_exit: module.add_function("moo_exit", void_type.fn_type(mv1, false), None),
            moo_to_number: decl_mv_mv!("moo_to_number", mv1),
            moo_args: decl_mv_mv!("moo_args", &[]),
            moo_pid: decl_mv_mv!("moo_pid", &[]),
            // Tray (erweitert — moo_tray.h)
            moo_tray_create: decl_mv_mv!("moo_tray_create", mv2),
            moo_tray_titel_setze: decl_mv_mv!("moo_tray_titel_setze", mv2),
            moo_tray_icon_setze: decl_mv_mv!("moo_tray_icon_setze", mv2),
            moo_tray_aktiv: decl_mv_mv!("moo_tray_aktiv", mv2),
            moo_tray_menu_add: decl_mv_mv!("moo_tray_menu_add", mv3),
            moo_tray_separator_add: decl_mv_mv!("moo_tray_separator_add", mv1),
            moo_tray_menu_clear: decl_mv_mv!("moo_tray_menu_clear", mv1),
            moo_tray_submenu_add: decl_mv_mv!("moo_tray_submenu_add", mv2),
            moo_tray_menu_add_to: decl_mv_mv!("moo_tray_menu_add_to", mv3),
            moo_tray_separator_add_to: decl_mv_mv!("moo_tray_separator_add_to", mv1),
            moo_tray_check_add: decl_mv_mv!("moo_tray_check_add", &[mv, mv, mv, mv]),
            moo_tray_check_add_to: decl_mv_mv!("moo_tray_check_add_to", &[mv, mv, mv, mv]),
            moo_tray_check_wert: decl_mv_mv!("moo_tray_check_wert", mv1),
            moo_tray_check_set: decl_mv_mv!("moo_tray_check_set", mv2),
            moo_tray_item_aktiv: decl_mv_mv!("moo_tray_item_aktiv", mv2),
            moo_tray_item_label_setze: decl_mv_mv!("moo_tray_item_label_setze", mv2),
            moo_tray_timer_add: decl_mv_mv!("moo_tray_timer_add", mv2),
            moo_tray_timer_remove: decl_mv_mv!("moo_tray_timer_remove", mv1),
            moo_tray_run: decl_mv_mv!("moo_tray_run", &[]),
            // UI (Cross-Platform — moo_ui.h)
            moo_ui_init: decl_mv_mv!("moo_ui_init", &[]),
            moo_ui_laufen: decl_mv_mv!("moo_ui_laufen", &[]),
            moo_ui_beenden: decl_mv_mv!("moo_ui_beenden", &[]),
            moo_ui_pump: decl_mv_mv!("moo_ui_pump", &[]),
            moo_ui_debug: decl_mv_mv!("moo_ui_debug", mv1),
            moo_ui_fenster: decl_mv_mv!("moo_ui_fenster", &[mv, mv, mv, mv, mv]),
            moo_ui_fenster_titel_setze: decl_mv_mv!("moo_ui_fenster_titel_setze", mv2),
            moo_ui_fenster_icon_setze: decl_mv_mv!("moo_ui_fenster_icon_setze", mv2),
            moo_ui_fenster_groesse_setze: decl_mv_mv!("moo_ui_fenster_groesse_setze", mv3),
            moo_ui_fenster_position_setze: decl_mv_mv!("moo_ui_fenster_position_setze", mv3),
            moo_ui_fenster_schliessen: decl_mv_mv!("moo_ui_fenster_schliessen", mv1),
            moo_ui_zeige: decl_mv_mv!("moo_ui_zeige", mv1),
            moo_ui_zeige_nebenbei: decl_mv_mv!("moo_ui_zeige_nebenbei", mv1),
            moo_ui_fenster_on_close: decl_mv_mv!("moo_ui_fenster_on_close", mv2),
            moo_ui_fenster_on_resize: decl_mv_mv!("moo_ui_fenster_on_resize", mv2),
            moo_ui_label: decl_mv_mv!("moo_ui_label", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_label_setze: decl_mv_mv!("moo_ui_label_setze", mv2),
            moo_ui_label_text: decl_mv_mv!("moo_ui_label_text", mv1),
            moo_ui_knopf: decl_mv_mv!("moo_ui_knopf", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_checkbox: decl_mv_mv!("moo_ui_checkbox", &[mv, mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_checkbox_wert: decl_mv_mv!("moo_ui_checkbox_wert", mv1),
            moo_ui_checkbox_setze: decl_mv_mv!("moo_ui_checkbox_setze", mv2),
            moo_ui_radio: decl_mv_mv!("moo_ui_radio", &[mv, mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_radio_wert: decl_mv_mv!("moo_ui_radio_wert", mv1),
            moo_ui_eingabe: decl_mv_mv!("moo_ui_eingabe", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_eingabe_text: decl_mv_mv!("moo_ui_eingabe_text", mv1),
            moo_ui_eingabe_setze: decl_mv_mv!("moo_ui_eingabe_setze", mv2),
            moo_ui_eingabe_on_change: decl_mv_mv!("moo_ui_eingabe_on_change", mv2),
            moo_ui_eingabe_on_enter: decl_mv_mv!("moo_ui_eingabe_on_enter", mv2),
            moo_ui_textbereich: decl_mv_mv!("moo_ui_textbereich", &[mv, mv, mv, mv, mv]),
            moo_ui_textbereich_text: decl_mv_mv!("moo_ui_textbereich_text", mv1),
            moo_ui_textbereich_setze: decl_mv_mv!("moo_ui_textbereich_setze", mv2),
            moo_ui_textbereich_anhaengen: decl_mv_mv!("moo_ui_textbereich_anhaengen", mv2),
            moo_ui_textbereich_on_key: decl_mv_mv!("moo_ui_textbereich_on_key", mv2),
            moo_ui_textbereich_zeile_anzahl: decl_mv_mv!("moo_ui_textbereich_zeile_anzahl", mv1),
            moo_ui_dropdown: decl_mv_mv!("moo_ui_dropdown", &[mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_dropdown_auswahl: decl_mv_mv!("moo_ui_dropdown_auswahl", mv1),
            moo_ui_dropdown_auswahl_setze: decl_mv_mv!("moo_ui_dropdown_auswahl_setze", mv2),
            moo_ui_dropdown_text: decl_mv_mv!("moo_ui_dropdown_text", mv1),
            moo_ui_liste: decl_mv_mv!("moo_ui_liste", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_liste_zeile_hinzu: decl_mv_mv!("moo_ui_liste_zeile_hinzu", mv2),
            moo_ui_liste_auswahl: decl_mv_mv!("moo_ui_liste_auswahl", mv1),
            moo_ui_liste_zeile: decl_mv_mv!("moo_ui_liste_zeile", mv2),
            moo_ui_liste_leeren: decl_mv_mv!("moo_ui_liste_leeren", mv1),
            moo_ui_liste_on_auswahl: decl_mv_mv!("moo_ui_liste_on_auswahl", mv2),
            moo_ui_liste_on_scroll: decl_mv_mv!("moo_ui_liste_on_scroll", mv2),
            moo_ui_liste_scroll_zu: decl_mv_mv!("moo_ui_liste_scroll_zu", mv2),
            moo_ui_liste_scroll_unten: decl_mv_mv!("moo_ui_liste_scroll_unten", mv1),
            moo_ui_liste_spalte_breite: decl_mv_mv!("moo_ui_liste_spalte_breite", mv3),
            moo_ui_liste_sortierbar: decl_mv_mv!("moo_ui_liste_sortierbar", mv3),
            moo_ui_liste_sortiere: decl_mv_mv!("moo_ui_liste_sortiere", mv3),
            moo_ui_liste_zeile_setze: decl_mv_mv!("moo_ui_liste_zeile_setze", mv3),
            moo_ui_liste_zelle_setze: decl_mv_mv!("moo_ui_liste_zelle_setze", &[mv, mv, mv, mv]),
            moo_ui_liste_entferne: decl_mv_mv!("moo_ui_liste_entferne", mv2),
            moo_ui_slider: decl_mv_mv!("moo_ui_slider", &[mv, mv, mv, mv, mv, mv, mv, mv, mv]),
            moo_ui_slider_wert: decl_mv_mv!("moo_ui_slider_wert", mv1),
            moo_ui_slider_setze: decl_mv_mv!("moo_ui_slider_setze", mv2),
            moo_ui_fortschritt: decl_mv_mv!("moo_ui_fortschritt", &[mv, mv, mv, mv, mv]),
            moo_ui_fortschritt_setze: decl_mv_mv!("moo_ui_fortschritt_setze", mv2),
            moo_ui_bild: decl_mv_mv!("moo_ui_bild", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_bild_setze: decl_mv_mv!("moo_ui_bild_setze", mv2),
            moo_ui_leinwand: decl_mv_mv!("moo_ui_leinwand", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_leinwand_anfordern: decl_mv_mv!("moo_ui_leinwand_anfordern", mv1),
            moo_ui_leinwand_on_maus: decl_mv_mv!("moo_ui_leinwand_on_maus", mv2),
            moo_ui_leinwand_on_bewegung: decl_mv_mv!("moo_ui_leinwand_on_bewegung", mv2),
            moo_ui_zeichne_farbe: decl_mv_mv!("moo_ui_zeichne_farbe", &[mv, mv, mv, mv, mv]),
            moo_ui_zeichne_linie: decl_mv_mv!("moo_ui_zeichne_linie", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_zeichne_rechteck: decl_mv_mv!("moo_ui_zeichne_rechteck", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_zeichne_kreis: decl_mv_mv!("moo_ui_zeichne_kreis", &[mv, mv, mv, mv, mv]),
            moo_ui_zeichne_text: decl_mv_mv!("moo_ui_zeichne_text", &[mv, mv, mv, mv, mv]),
            moo_ui_zeichne_text_breite: decl_mv_mv!("moo_ui_zeichne_text_breite", mv3),
            moo_ui_zeichne_bild: decl_mv_mv!("moo_ui_zeichne_bild", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_rahmen: decl_mv_mv!("moo_ui_rahmen", &[mv, mv, mv, mv, mv, mv]),
            moo_ui_trenner: decl_mv_mv!("moo_ui_trenner", &[mv, mv, mv, mv, mv]),
            moo_ui_tabs: decl_mv_mv!("moo_ui_tabs", &[mv, mv, mv, mv, mv]),
            moo_ui_tab_hinzu: decl_mv_mv!("moo_ui_tab_hinzu", mv2),
            moo_ui_tabs_auswahl: decl_mv_mv!("moo_ui_tabs_auswahl", mv1),
            moo_ui_tabs_auswahl_setze: decl_mv_mv!("moo_ui_tabs_auswahl_setze", mv2),
            moo_ui_scroll: decl_mv_mv!("moo_ui_scroll", &[mv, mv, mv, mv, mv]),
            moo_ui_sichtbar: decl_mv_mv!("moo_ui_sichtbar", mv2),
            moo_ui_aktiv: decl_mv_mv!("moo_ui_aktiv", mv2),
            moo_ui_position_setze: decl_mv_mv!("moo_ui_position_setze", mv3),
            moo_ui_groesse_setze: decl_mv_mv!("moo_ui_groesse_setze", mv3),
            moo_ui_farbe_setze: decl_mv_mv!("moo_ui_farbe_setze", mv2),
            moo_ui_schrift_setze: decl_mv_mv!("moo_ui_schrift_setze", mv3),
            moo_ui_tooltip_setze: decl_mv_mv!("moo_ui_tooltip_setze", mv2),
            moo_ui_zerstoere: decl_mv_mv!("moo_ui_zerstoere", mv1),
            moo_ui_widget_id_setze: decl_mv_mv!("moo_ui_widget_id_setze", mv2),
            moo_ui_widget_id_hole: decl_mv_mv!("moo_ui_widget_id_hole", mv1),
            moo_ui_widget_info: decl_mv_mv!("moo_ui_widget_info", mv1),
            moo_ui_widget_baum: decl_mv_mv!("moo_ui_widget_baum", mv1),
            moo_ui_widget_suche: decl_mv_mv!("moo_ui_widget_suche", mv2),
            moo_ui_test_snapshot: decl_mv_mv!("moo_ui_test_snapshot", mv2),
            moo_ui_test_snapshot_widget: decl_mv_mv!("moo_ui_test_snapshot_widget", mv2),
            moo_ui_test_klick: decl_mv_mv!("moo_ui_test_klick", mv1),
            moo_ui_test_klick_xy: decl_mv_mv!("moo_ui_test_klick_xy", mv3),
            moo_ui_test_text_setze: decl_mv_mv!("moo_ui_test_text_setze", mv2),
            moo_ui_test_shortcut: decl_mv_mv!("moo_ui_test_shortcut", mv2),
            moo_ui_test_warte: decl_mv_mv!("moo_ui_test_warte", mv1),
            moo_ui_test_pump: decl_mv_mv!("moo_ui_test_pump", &[]),
            moo_ui_timer_hinzu: decl_mv_mv!("moo_ui_timer_hinzu", mv2),
            moo_ui_timer_entfernen: decl_mv_mv!("moo_ui_timer_entfernen", mv1),
            moo_ui_info: decl_mv_mv!("moo_ui_info", mv3),
            moo_ui_warnung: decl_mv_mv!("moo_ui_warnung", mv3),
            moo_ui_fehler: decl_mv_mv!("moo_ui_fehler", mv3),
            moo_ui_frage: decl_mv_mv!("moo_ui_frage", mv3),
            moo_ui_eingabe_dialog: decl_mv_mv!("moo_ui_eingabe_dialog", &[mv, mv, mv, mv]),
            moo_ui_datei_oeffnen: decl_mv_mv!("moo_ui_datei_oeffnen", mv3),
            moo_ui_datei_speichern: decl_mv_mv!("moo_ui_datei_speichern", mv3),
            moo_ui_ordner_waehlen: decl_mv_mv!("moo_ui_ordner_waehlen", mv2),
            moo_ui_menueleiste: decl_mv_mv!("moo_ui_menueleiste", mv1),
            moo_ui_menue: decl_mv_mv!("moo_ui_menue", mv2),
            moo_ui_menue_eintrag: decl_mv_mv!("moo_ui_menue_eintrag", mv3),
            moo_ui_menue_trenner: decl_mv_mv!("moo_ui_menue_trenner", mv1),
            moo_ui_menue_untermenue: decl_mv_mv!("moo_ui_menue_untermenue", mv2),
            moo_ui_shortcut_bind: decl_mv_mv!("moo_ui_shortcut_bind", mv3),
            moo_ui_shortcut_loese: decl_mv_mv!("moo_ui_shortcut_loese", mv2),
            // Netzwerk
            moo_tcp_server: decl_mv_mv!("moo_tcp_server", mv1),
            moo_tcp_connect: decl_mv_mv!("moo_tcp_connect", mv2),
            moo_udp_socket: decl_mv_mv!("moo_udp_socket", mv1),
            moo_udp_connect: module.add_function("moo_udp_connect", void_type.fn_type(mv3, false), None),
            moo_socket_accept: decl_mv_mv!("moo_socket_accept", mv1),
            moo_socket_read: decl_mv_mv!("moo_socket_read", mv2),
            moo_socket_write: module.add_function("moo_socket_write", void_type.fn_type(mv2, false), None),
            // Profiler
            moo_profile_enter: module.add_function("moo_profile_enter", void_type.fn_type(mv1, false), None),
            moo_profile_exit: module.add_function("moo_profile_exit", void_type.fn_type(mv1, false), None),
            moo_profile_report: module.add_function("moo_profile_report", void_type.fn_type(&[], false), None),
            // Webserver
            // Eval
            moo_eval: decl_mv_mv!("moo_eval", mv1),
            // Webserver
            moo_web_server: decl_mv_mv!("moo_web_server", mv1),
            moo_web_accept: decl_mv_mv!("moo_web_accept", mv1),
            moo_web_respond: decl_mv_mv!("moo_web_respond", mv3),
            moo_web_json: decl_mv_mv!("moo_web_json", mv2),
            moo_web_respond_with_headers: decl_mv_mv!("moo_web_respond_with_headers", &[mv, mv, mv, mv]),
            moo_web_json_with_headers: decl_mv_mv!("moo_web_json_with_headers", &[mv, mv, mv, mv]),
            moo_web_file: decl_mv_mv!("moo_web_file", mv2),
            moo_web_template: decl_mv_mv!("moo_web_template", mv3),
        }
    }
}
