# Variante A: Named-Params (:name)
setze db auf db_verbinde("sqlite://memory")
db_ausführen(db, "CREATE TABLE u (id INTEGER PRIMARY KEY, name TEXT, age INTEGER)")
setze stmt auf db_vorbereite(db, "INSERT INTO u (name, age) VALUES (:name, :age)")
stmt.binde(":name", "Anna")
stmt.binde(":age", 25)
stmt.ausfuehren()
stmt.binde("name", "Bob")
stmt.binde("age", 30)
stmt.ausfuehren()
stmt.schliessen()
setze q auf db_vorbereite(db, "SELECT name, age FROM u WHERE age > :min ORDER BY age")
q.binde(":min", 20)
setze rows auf q.abfrage()
zeige rows
q.schliessen()
db_schliessen(db)
